/**
 * Checkout's words in the app (Docs/pos-retail-ux-spec.md §18 on the web), keyed by the web's copy
 * ids and written word for word from the copy deck. The web's till keeps the same deck in
 * `src/components/pos/copy.ts`; the entries below are copied from it unchanged (UX spec §13: the app
 * keeps its own copy file and reuses the web's ids), then the app's own `app.*` strings follow.
 *
 * Placeholders are in {braces}. `{client}` and `{Client}` are the venue's own word for its clients,
 * filled by `usePosCopy`. Money arrives already formatted, so no currency symbol sits next to a
 * money placeholder.
 *
 * Rules `copy.test.ts` enforces: no em-dash anywhere, straight apostrophes, and every placeholder a
 * caller can fill.
 */
export const POS_COPY = {
  // §18.1 Common
  'common.cancel': 'Cancel',
  'common.save': 'Save changes',
  'common.tryAgain': 'Try again',
  'common.networkError': "We couldn't reach ResNeo. Check your connection and try again.",
  'common.saveError': "We couldn't save that. Please try again.",

  // §18.2 Navigation, Sales history and support sessions
  'nav.checkout': 'Checkout',
  'hist.banner': 'Checkout is switched off for {venue}. You can still see past sales and give refunds.',
  'hist.link': 'Sales history',
  'support.banner':
    "You're signed in as ResNeo support. You can look at everything, but you can't take payments, refund, void, cash up or add card readers.",
  'support.disabled': "ResNeo support can't do this.",

  // §18.3 Checkout home, queue and sales lists
  'till.title': 'Checkout',
  'till.newSale': 'New sale',
  'till.tab.queue': 'Ready to check out',
  'till.tab.open': 'Open sales',
  'till.tab.all': 'All sales',
  'till.live': 'Live',
  'till.reconnecting': 'Reconnecting',
  'till.device.chip': 'Till: {till}',
  'till.device.title': 'Which till is this?',
  'till.device.body':
    'Choose the till this device is used at. Cash and card reader payments are recorded against it. You can change it later.',
  'till.device.confirm': 'Use this till',
  'till.error.title': "We couldn't open Checkout",
  'till.error.body': 'Something went wrong loading your till. Please try again.',
  'till.off.title': "Checkout isn't switched on",
  'till.off.body': "Checkout isn't available for {venue} yet. If you think it should be, contact ResNeo support.",
  'till.lapsed.title': 'Your plan needs attention',
  'till.lapsed.body':
    "You can't take new payments until your subscription is sorted. You can still see sales, give refunds, cash up and hand over paid orders.",
  'till.currency.title': 'Checkout works in pounds for now',
  'till.currency.body':
    "{venue} uses {currency}, and Checkout only works in pounds in this version. We'll let you know when euros are supported.",
  'queue.date': 'Day',
  'queue.filter.mine': 'Only mine',
  'queue.due': '{amount} to pay',
  'queue.status.started': 'In progress',
  'queue.status.completed': 'Completed',
  'queue.status.arrived': 'Arrived',
  'queue.chip.deposit': 'Deposit paid {amount}',
  'queue.chip.openSale': 'Sale {saleNo} open',
  'queue.chip.class': '{modelName} booking',
  'queue.chip.noPrice': 'No price yet',
  'queue.chip.reward': 'Reward ready',
  'queue.checkout': 'Check out',
  'queue.empty.title': 'Nobody waiting to pay',
  'queue.empty.body':
    'When a {client} arrives, or their appointment starts or finishes, they appear here so you can check them out in one tap.',
  'queue.error': "We couldn't load who's ready to pay.",
  'sales.walkIn': 'Walk-in',
  'sales.items': '{count} items',
  'sales.items.one': '1 item',
  'sales.pill.cardPending': 'Card payment in progress',
  'sales.parkedBy': 'Parked by {staffName} on {device} at {time}',
  'sales.startedBy': 'Started by {staffName} at {time}',
  'sales.resume': 'Resume',
  'sales.filter.all': 'All',
  'sales.filter.parked': 'Parked',
  'sales.filter.partPaid': 'Part paid',
  'sales.filter.mine': 'Mine',
  'sales.empty.title': 'No open sales',
  'sales.empty.body': 'Sales you park, or leave part paid, wait here for anyone to finish on any device.',
  'sales.search': 'Search by sale number, name or amount',
  'sales.filter.dates': 'Dates',
  'sales.filter.status': 'Status',
  'sales.channel.till': 'Till',
  'sales.channel.app': 'App',
  'sales.channel.online': 'Online',
  'sales.filter.refunded': 'Refunded',
  'sales.loadMore': 'Show more',
  'sales.none.filtered': 'No sales match these filters.',

  // §18.4 The sale screen, lines and totals
  'sale.title': 'Sale {saleNo}',
  'sale.status.open': 'Open',
  'sale.status.parked': 'Parked',
  'sale.status.part_paid': 'Part paid',
  'sale.status.completed': 'Paid',
  'sale.status.voided': 'Voided',
  'sale.status.pending_payment': 'Waiting for payment',
  'sale.status.expired': 'Expired',
  'sale.refund.partial': 'Part refunded',
  'sale.refund.full': 'Refunded',
  'sale.more': 'More',
  'sale.park': 'Park sale',
  'sale.addBooking': 'Add another booking',
  'sale.notes': 'Add a note',
  'sale.notes.label': 'Note',
  'sale.notes.help': "Only your team sees this. It isn't printed on receipts.",
  'sale.void': 'Void sale',
  'sale.discount': 'Add a discount',
  'sale.bar.balance': '{balance} to pay',
  'sale.pay.open': 'Take payment',
  'sale.notFound.title': "We can't find this sale",
  'sale.notFound.body': 'It may belong to another venue, or the link is wrong.',
  'sale.notFound.back': 'Back to Checkout',
  'sale.completedLine': 'Paid on {date} at {time}. Served by {staffName}.',
  'sale.voidedLine': 'Voided on {date} at {time} by {staffName}: {reason}',
  'sale.refundAndVoid': 'Refund and cancel',
  'sale.done.receipt': 'Send receipt',
  'sale.done.refund': 'Refund',
  'line.qtyPrefix': '{count} x',
  'line.chip.discount': '{amount} off',
  'line.chip.priceChanged': 'Price changed from {listPrice}',
  'line.chip.paid': 'Paid',
  'line.chip.walkIn': "Walk-in, in {staffName}'s diary",
  'line.chip.custom': 'Custom item',
  'line.chip.fee': 'Fee',
  'line.chip.age18': '18+',
  'line.class.credit': 'Paid with {entitlement}',
  'totals.subtotal': 'Subtotal',
  'totals.discounts': 'Discounts',
  'totals.total': 'Total',
  'totals.vatIncluded': 'Includes VAT of {amount}',
  'totals.depositApplied': 'Deposit paid online',
  'totals.priorPayment': 'Paid earlier',
  'totals.returned': 'Returned',
  'totals.paid': 'Paid today',
  'totals.pending': 'Payment in progress',
  'totals.linkReserved': 'On pay links sent',
  'totals.balance': 'Still to pay',
  'totals.balanceZero': 'Nothing left to pay',
  'totals.tips': 'Tips',
  'totals.tips.note': "Tips aren't part of the total.",

  // §18.5 Adding items
  'add.open': 'Add items',
  'add.done': 'Done',
  'add.search.placeholder': 'Search services and products, or scan a barcode',
  'add.tab.favourites': 'Favourites',
  'add.tab.services': 'Services',
  'add.tab.custom': 'Custom',
  'add.options': '{count} options',
  'add.options.one': '1 option',
  'add.from': 'From {amount}',
  'add.none': 'Nothing matches "{query}".',
  'add.fav.empty': 'No favourites yet. Add the things you sell most, for one-tap selling.',
  'add.fav.suggested': 'Your best sellers from the last 30 days. An admin can choose your own.',
  'add.fee': 'Add a fee',
  'walkin.title': 'Who did this service?',
  'walkin.body':
    "We'll add it to their diary as a walk-in that ends now, so their day and the {client}'s history stay right.",
  'walkin.option': 'Option',
  'walkin.sameVisit': 'It joins the visit already on this sale.',
  'walkin.confirm': 'Add service',
  'custom.name': 'Item name',
  'custom.price': 'Price',
  'custom.kind': 'Counts as',
  'custom.kind.service': 'A service',
  'custom.kind.product': 'A product',
  'custom.kind.other': 'Something else',
  'custom.vat': 'VAT rate',
  'custom.add': 'Add to sale',
  'fee.lateCancel': 'Late cancellation fee',
  'fee.noShow': 'No-show fee',
  'fee.other': 'Another fee',
  'fee.help': 'For a fee paid at the desk. Fees already charged to a saved card show on the booking, not here.',
  'fee.add': 'Add fee',
  'age.reminder': 'Check the {client} is 18 or over before you sell {product}.',

  // §18.6 The line editor and credit
  'line.option': 'Option',
  'line.qty': 'Quantity',
  'line.qty.fixed': 'Set by the booking',
  'line.price': 'Price',
  'line.price.change': 'Change price',
  'line.remove': 'Remove from sale',
  'line.remove.booking': 'Take off this sale',
  'line.remove.bookingConfirm.title': 'Take {service} off this sale?',
  'line.remove.bookingConfirm.body': 'The booking stays in the diary, and you can check it out on its own.',
  'line.remove.walkInConfirm.body':
    "This takes it off the sale and cancels the walk-in booking it added to {staffName}'s diary.",
  'line.save': 'Done',
  'price.reason': 'Reason for the change',
  'price.reason.longer': 'Took longer than booked',
  'price.reason.shorter': 'Shorter than booked',
  'price.reason.match': 'Price match',
  'price.reason.correction': 'Correcting a mistake',
  'price.help': 'We keep the original price for your records and reports.',
  'price.reset': 'Use the original price',
  'attr.title': 'Who gets credit for {item}?',
  'attr.help': "Credit is used in sales reports and for tips. It doesn't change the diary.",
  'attr.reason': 'Why are you changing who gets credit?',
  'attr.sharedReadOnly': 'Shared between {names}. To change it, choose one person.',

  // §18.7 The client on a sale
  'client.add': 'Add {client}',
  'client.open': 'Open profile',
  'client.change': 'Change {client}',
  'client.remove': 'Remove from sale',
  'client.title': 'Add a {client}',
  'client.search': 'Search by name, phone or email',
  'client.new': 'New {client}',
  'client.walkIn': 'Carry on without a {client}',
  'client.changeBooking': 'The bookings on this sale stay with {clientName}. Only the sale changes.',

  // §18.8 Discounts
  'disc.title': 'Add a discount',
  'disc.scope.sale': 'Whole sale',
  'disc.scope.line': '{item} only',
  'disc.tab.manual': 'Percent or amount',
  'disc.tab.preset': 'Presets',
  'disc.kind.percent': 'Percent',
  'disc.kind.amount': 'Amount',
  'disc.reason': 'Reason',
  'disc.reason.other': 'Other',
  'disc.preview': 'Takes {amount} off. New total {total}.',
  'disc.preset.max': 'Up to {amount}',
  'disc.apply': 'Apply discount',
  'disc.remove': 'Remove discount',

  // §18.9 Combine, park and void
  'attach.title': 'Add another booking',
  'attach.body': 'For one person paying for another visit, like a parent paying for a child.',
  'attach.search': "Search today's bookings",
  'attach.sales': 'Or combine with an open sale',
  'attach.done': "Added {clientName}'s booking to this sale.",
  'attach.inOtherSale': 'That booking is already on Sale {saleNo}. Open that sale, or combine the two into this one?',
  'attach.openOther': 'Open Sale {saleNo}',
  'attach.combine': 'Combine sales',
  'attach.pendingBlock': 'You can combine these once no payment is in progress on either sale.',
  'attach.bothPaid': "Both sales already have payments, so they can't be combined. Finish each one on its own.",
  'attach.movedInto': 'Combined into Sale {saleNo}, which already had a payment.',
  'park.title': 'Park this sale?',
  'park.body': 'It waits in Open sales, so anyone can finish it on any device.',
  'park.note': 'Note (optional)',
  'park.confirm': 'Park sale',
  'park.done': 'Sale {saleNo} parked.',
  'park.banner': 'Parked by {staffName} on {device} at {time}. {note}',
  'park.resume': 'Resume',
  'void.title': 'Void Sale {saleNo}?',
  'void.body': 'The sale is cancelled and kept in your records as voided. Use this for mistakes.',
  'void.bookings': 'The bookings on it go back to unpaid, so they can be checked out again.',
  'void.walkIns': 'Walk-in services added on this sale are cancelled in the diary too.',
  'void.reason': 'Reason',
  'void.confirm': 'Void sale',
  'rv.pending': "We'll void the sale once the card refund is confirmed. This usually takes a few seconds.",
  'rv.failed':
    "A card refund didn't go through, so the sale is still part paid. Refund that payment another way to finish cancelling.",

  // §18.10 Who is serving
  'serving.chip': 'Serving: {staffName}',
  'serving.title': "Who's serving?",
  'serving.search': 'Search the team',
  'serving.help':
    'Sales and tips are credited to the person serving. What anyone can do still depends on who is signed in.',
  'serving.adminDevice':
    'This device is signed in as {loginName}, an admin, so whoever is serving can do everything an admin can.',

  // §18.11 Tips
  'tip.label': 'Tip',
  'tip.none': 'No tip',
  'tip.add': 'Add a tip',
  'tip.preset': '{percent}% ({amount})',
  'tip.preset.amount': '{amount}',
  'tip.custom': 'Another amount',
  'tip.noTip': 'No tip',
  'tip.base.services': 'Percentages are worked out on services only ({amount}).',
  'tip.base.total': 'Percentages are worked out on the whole bill ({amount}).',
  'tip.goesTo': 'Goes to {allocation}',
  'tip.goesTo.change': 'Change',
  'tip.rule.pro_rata_services': 'In proportion to their services',
  'tip.rule.equal_performers': 'Equally between the people who did the services',
  'tip.rule.operator': 'All to {staffName}',
  'tip.rule.manual': 'Choose amounts',
  'tip.alloc.total': 'Shared {allocated} of {tip}',
  'tip.alloc.reason': 'Why are you changing it?',
  'tip.retailOnly': 'Tips on product-only sales go to whoever sold them.',
  'tip.policy.link': 'Read the tipping policy',

  // §18.12 The payment panel
  'pay.title': 'Take payment',
  'pay.noPermission': "You can't take payments on this login. Ask an admin to take it, or to give you permission.",
  'pay.amount': 'Amount to pay now',
  'pay.amount.part': 'Paying part now leaves {remaining} to pay.',
  'pay.splitEvenly': 'Split evenly',
  'pay.method.cash': 'Cash',
  'pay.method.other': 'Other: {typeName}',
  'pay.locked': 'Finish or cancel the payment in progress first.',
  'pay.list': 'Payments on this sale',
  'pay.status.pending': 'In progress',
  'pay.status.succeeded': 'Paid',
  'pay.status.failed': 'Failed',
  'pay.status.cancelled': 'Cancelled',
  'pay.otherWay': 'Choose another way to pay',
  'pay.applied.deposit': 'Deposit paid online',
  'pay.applied.prior': 'Paid earlier',
  'pay.finish': 'Complete',
  'pay.finish.help': 'This is already paid in full. Add anything else, or press Complete to finish.',
  'cash.title': 'Cash',
  'cash.due': '{amount} to pay',
  'cash.tendered': 'Cash handed over',
  'cash.exact': 'Exact amount',
  'cash.change': 'Change to give: {amount}',
  'cash.keepChange': 'Keep the change as a tip ({amount})',
  'cash.confirm': 'Record {amount} in cash',
  'other.help':
    'For money taken outside ResNeo, like another card machine or a bank transfer. It shows in your takings under its own name.',
  'other.reference': 'Reference',
  'other.reference.required': "Add the reference, like the last four digits on the card machine's slip.",
  'other.confirm': 'Record {amount} by {typeName}',
  'part.banner': '{paid} paid. {balance} still to pay.',
  'part.park': 'Finish later',

  // §18.13 Completion and a completed sale
  'done.title': 'Paid in full',
  'done.titleZero': 'All done',
  'done.change': 'Give {amount} change',
  'done.summary': '{total} paid by {methods}',
  'done.tip': 'Tip {amount}, going to {allocation}',
  'done.receipt.email': 'Email receipt',
  'done.receipt.text': 'Text receipt',
  'done.receipt.none': 'No receipt',
  'done.receipt.to': 'Email address or mobile number',
  'done.receipt.sentAuto': 'Receipt emailed to {email}.',
  'done.receipt.sent': 'Receipt sent to {destination}.',
  'done.bookNext': 'Book next appointment',
  'done.next': 'Next {client}',
  'done.newSale': 'New sale',
  'done.tips.change': 'Change tip split',
  'done.credit.change': 'Change who gets credit',

  // §18.14 Refunds
  'refund.title': 'Refund Sale {saleNo}',
  'refund.what': 'What are you refunding?',
  'refund.byItems': 'Items',
  'refund.byAmount': 'An amount',
  'refund.bookingLine': "The booking itself isn't changed.",
  'refund.tip': 'Also refund the tip ({tip})',
  'refund.where': 'Where should the money go?',
  'refund.dest.original': 'Back to {method}',
  'refund.dest.cash': 'Cash from the till',
  'refund.dest.other': 'Another way',
  'refund.spans': 'This refund is split across {count} payments, cards first.',
  'refund.reason': 'Reason',
  'refund.note': 'Note (optional)',
  'refund.summary': 'Refund {amount} to {destination}',
  'refund.confirm': 'Refund {amount}',
  'refund.sentCard': "Refund sent. It usually reaches {clientName}'s account in 5 to 10 working days.",
  'refund.doneCash': 'Give {clientName} {amount} from the till.',
  'refund.doneOther': 'Refund of {amount} recorded as {typeName}.',
  'refund.failed':
    "The card refund didn't go through: {reason}. Refund in cash or another way. Any items returned stay recorded.",
  'refund.waitingFunds':
    "Stripe is holding this refund until there's enough in your Stripe balance. It goes through by itself as new payments come in. If {clientName} needs it now, refund another way.",
  'refund.external': 'Refunded in Stripe',
  'refund.external.note':
    "Someone refunded this in your Stripe dashboard, so we've recorded it here. No items were put back in stock.",
  'refund.status.pending': 'Processing',
  'refund.status.waitingFunds': 'Waiting for funds',
  'refund.status.succeeded': 'Refunded',
  'refund.status.failed': 'Failed',

  // §18.15 Stale sales and offline
  'stale.notice': "This sale was changed on another device, so we've loaded the latest version. Check it, then carry on.",
  'stale.dialog': 'This sale changed while you were working. Check the details, then apply again.',
  'stale.payment':
    "The sale changed before the payment started, so nothing was taken. It's now {balance} to pay. Check it, then take payment again.",
  'stale.live': 'Updated just now on another device.',
  'stale.closed.completed': 'This sale was paid on another device.',
  'stale.closed.voided': 'This sale was voided on another device.',
  'offline.banner': "You're offline. Everything up to your last change is saved. We'll carry on when you're back.",
  'offline.disabled': 'Reconnect to do this.',

  // §18.16 Error sentences the till fills itself (the server writes the rest)
  'err.POS_AMOUNT_EXCEEDS_BALANCE': "That's more than the {balance} still to pay. Enter {balance} or less.",
  'err.ceiling':
    "That's more than {max}, the largest single payment {venue} allows. Check the amount, or ask an admin to change the limit in Settings, Checkout.",
  'err.attachConflict': "That booking is already on Sale {saleNo}, which has been paid, so it can't be added here.",
  'err.POS_TIPS_DO_NOT_ADD_UP': 'The shares add up to {allocated}, but the tip is {tip}. Change them so they add up to {tip}.',

  // §18.17 Booking detail and calendar
  'bk.checkout': 'Check out',
  'bk.checkout.opening': 'Opening checkout…',
  'bk.takeFee': 'Take a fee',
  'cal.checkout': 'Check out',
  'cal.checkout.short': 'Pay',

  // §18.31 Hard limits
  'limit.discount': "That's more than your {limit}% discount limit. An admin can give a bigger discount.",
  'limit.price': "You can't change prices on your login. An admin can change it for you.",
  'limit.refund': "You can't give refunds on your login. An admin can give this refund.",
  'limit.refundMethod': 'Only an admin can refund to a different method from the original payment.',
  'limit.howTo':
    'Park the sale if you need to. An admin can open it on their own login, on any device or in the app, and finish it there.',

  // §18.32 Gift vouchers and account credit (Pass V), word for word from the web's
  // `src/components/pos/vouchers/voucher-copy.ts`: only the ids the app shows.
  'vch.ending': 'Gift voucher ending {last4}',
  'vch.status.active': 'Active',
  'vch.status.usedUp': 'Used up',
  'vch.status.expired': 'Expired',
  'vch.status.frozen': 'On hold',
  'vch.status.cancelled': 'Cancelled',
  'vch.balance': '{balance} left',
  'vch.expires': 'Use by {date}',
  'vch.noExpiry': 'No expiry date',
  'add.tab.vouchers': 'Gift vouchers',
  'vsell.preset': '{amount} gift voucher',
  'vsell.custom': 'Another amount',
  'vsell.title': 'Sell a gift voucher',
  'vsell.amount': 'Value',
  'vsell.amount.range': 'Between {min} and {max}',
  'vsell.amount.tooLow': 'The smallest voucher is {min}.',
  'vsell.amount.tooHigh': 'The largest voucher is {max}.',
  'vsell.who': "Who's it for?",
  'vsell.who.buyer': 'The person paying',
  'vsell.who.gift': 'A gift for someone else',
  'vsell.recipientName': 'Their name',
  'vsell.recipientEmail': 'Their email, to send it to them',
  'vsell.message': 'A message (optional)',
  'vsell.message.help': 'Printed on the voucher and in the email. Up to 300 characters.',
  'vsell.delivery': 'How should it reach them?',
  'vsell.delivery.print': 'Print it or hand it over now',
  'vsell.delivery.emailNow': 'Email it now',
  'vsell.delivery.emailLater': 'Email it on a date',
  'vsell.sendDate': 'Date to send',
  'vsell.sendDate.help': 'It arrives at about 8am that day.',
  'vsell.buyerEmail': 'Email for the receipt (optional)',
  'vsell.add': 'Add to sale',
  'line.voucher': 'Gift voucher, {amount}',
  'line.voucher.for': 'For {recipientName}',
  'line.voucher.delivery.print': 'To print or hand over',
  'line.voucher.delivery.now': "Emailed when it's paid for",
  'line.voucher.delivery.later': 'Emailed on {date}',
  'line.voucher.noDiscount': "Gift vouchers can't be discounted.",
  'totals.voucher': 'Gift voucher',
  'totals.credit': 'Account credit',
  'done.voucher.issued': 'Gift voucher ending {last4} is ready.',
  'done.voucher.pdf': 'Print or download the voucher',
  'done.voucher.scheduled': "We'll email it to {recipientName} on {date}.",
  'pay.method.voucher': 'Gift voucher',
  'pay.method.credit': 'Account credit',
  'pay.voucher.row': 'Gift voucher ending {last4}',
  'vpay.title': 'Pay with a gift voucher',
  'vpay.code': 'Voucher code',
  'vpay.code.help': 'Type the 12 characters, or scan the QR code on the voucher.',
  'vpay.code.invalid': "That doesn't look like a voucher code. Check it and try again.",
  'vpay.find': 'Find voucher',
  'vpay.found': 'Gift voucher ending {last4}',
  'vpay.balance': '{balance} left',
  'vpay.expires': 'Use by {date}',
  'vpay.noExpiry': 'No expiry date',
  'vpay.for': 'For {recipientName}',
  'vpay.amount': 'Amount to take',
  'vpay.amount.max': 'Up to {amount}',
  'vpay.confirm': 'Take {amount} from the voucher',
  'vpay.left': "Done. There's {balance} left on the voucher.",
  'vpay.useBalance': 'Take {balance}',
  'vpay.usedUp': 'This gift voucher has been used up.',
  'vpay.cancelled': "This gift voucher was cancelled, so it can't be used.",
  'vpay.notForVouchers': "Gift vouchers and account credit can't pay for another gift voucher. Take {amount} another way.",
  'cpay.title': 'Pay with account credit',
  'cpay.available': '{clientName} has {amount} credit',
  'cpay.amount': 'Amount to use',
  'cpay.confirm': 'Use {amount} of credit',
  'cpay.clientLocked':
    "Account credit has been used on this sale, so you can't change the {client}. Refund the credit payment first.",
  'refund.dest.credit': 'Account credit',
  'refund.dest.voucher': 'Back to the gift voucher ending {last4}',
  'refund.dest.voucherExpired': "The voucher has run out, so this goes to {clientName}'s account credit instead.",
  'refund.needsClient': 'Add the {client} first, so the credit has somewhere to go.',
  'refund.voucherLine': "Refunds what's left on the voucher ({balance}) and cancels it.",
  'refund.voucherUsed': 'Part of this voucher has been used, so only an admin can refund it.',
  'refund.voucherUsedUp': "This voucher has been used up, so there's nothing left to refund.",
  'err.VOUCHER_NOT_FOUND': "We can't find a gift voucher with that code at {venue}. Check the code and try again.",
  'err.VOUCHER_EXPIRED': "This gift voucher ran out on {date}. An admin can extend it if you're happy to take it.",
  // The server's sentence since 2026-10-09; the look-up's `on_hold` says when it is a dispute.
  'err.VOUCHER_FROZEN': "This gift voucher is on hold, so it can't be used yet. An admin can check why in Gift vouchers.",
  'err.VOUCHER_FROZEN.dispute': "This gift voucher is on hold while a payment dispute is open, so it can't be used yet.",
  'err.VOUCHER_INSUFFICIENT_BALANCE': 'This gift voucher only has {balance} left. Take {balance} from it, and the rest another way.',
  'err.CREDIT_INSUFFICIENT': '{clientName} only has {amount} of credit left.',
  'err.voucherLookupLimited': "That's a lot of codes in a short time. Wait a minute, then try again.",
  'client.sv.title': 'Credit and vouchers',
  'client.sv.credit': 'Account credit: {amount}',
  'client.sv.empty': 'No credit or gift vouchers yet.',

  // §18.28 The ResNeo app (staff)
  'app.tile.checkout': 'Checkout',
  'app.tile.checkout.hint': "Take payments and see today's sales",
  'app.tapToPay': 'Tap to Pay on this phone',
  'app.tapToPay.iphone': 'Tap to Pay on iPhone',
  'app.bluetoothReader': 'Card reader (Bluetooth)',
  'app.tip.title': 'Would you like to add a tip?',
  'app.receipt.share': 'Share PDF',
  'app.receipt.sentTo': 'Receipt sent to {destination}.',
  'app.receipt.notSent': 'No receipt sent.',
  'app.receipt.notSent.pos': 'No receipt sent. You can send one from the sale.',
  'app.balance.zero': 'Nothing left to pay',
  'app.reports.chips': 'Report tabs',
  'app.mine.title': 'Your sales and tips',
  'app.mine.today': 'Today',
  'app.mine.week': 'This week',
  'app.mine.sales': 'Sales credited to you: {amount}',
  'app.mine.tips': 'Your tips: {amount}',
  'app.mine.none': 'Nothing yet. Sales and tips credited to you will show here.',
  'app.web.group': 'On the web',
  'app.web.hint': 'Opens in your browser',
  'app.web.checkoutSettings': 'Checkout settings',
  'app.web.records': 'Records, reports and exports',
  'app.charge.timedOut': 'This payment timed out. Start it again.',

  // App-only words for a phone (UX spec §13.3: the app changes only what a phone needs)
  'app.pay.card': 'Card',
  'app.pay.cardHelp': 'Tap to Pay on this phone, or your Bluetooth card reader.',
  'app.pay.cardUnavailable': "Card payments can't be taken on this phone. Take cash or another way, or use the web till.",
  'app.pay.tipFirst': 'Choose a tip first, then hand over for the card.',
  'app.pay.withTip': 'Charge {amount}',
  'app.card.hold': "Hold the {client}'s card near the top of your phone.",
  'app.card.holdReader': 'Hold the card to the reader, or insert the chip.',
  'app.card.preparing': 'Getting the card reader ready.',
  'app.card.processing': 'Processing payment…',
  'app.card.cancel': 'Cancel',
  'app.card.back': 'Back',
  'app.card.retry': 'Try again',
  'app.card.useReader': 'Use card reader',
  'app.card.connectReader': 'Connect a card reader',
  'app.card.declined': 'The card was declined. Ask for another card, or take payment another way.',
  'app.card.notCompleted': "The payment didn't go through, so nothing was taken. Try again, or take payment another way.",
  'app.card.unsure':
    "We couldn't confirm the payment. Don't take it again: it will show on the sale by itself if it went through.",
  'app.card.cancelled': 'Payment cancelled. Nothing was taken.',
  'app.card.success': 'Paid {amount} by card.',
  'app.sale.serving': 'Serving',
  'app.sale.client': '{Client}',
  'app.sale.lines.empty': 'Nothing on this sale yet. Add a service, an item or a fee.',
  'app.sale.walkIn.choose': 'Choose who did it',
  'app.sale.reasonOther': 'Other reason',
  'app.sale.cardWaiting': 'A card payment is in progress on this sale.',
  'app.sale.cancelCard': 'Cancel the card payment',
  'app.sale.edit': 'Edit',
  'app.sale.backToSale': 'Back to the sale',
  'app.sale.custom.title': 'Add a custom item',
  'app.sale.fee.title': 'Add a fee',
  'app.sale.newSaleStarting': 'Starting a sale…',
  'app.sale.openFailed': "We couldn't open checkout. Please try again.",
  'app.sale.refundNothing': 'There is nothing left to refund on this sale.',
  'app.sale.refundFrom': 'From {method}',
  'app.sale.tipChange.title': 'Change tip split',
  'app.sale.tipChange.rule': 'Share it',
  'app.sale.credit.choose': 'Choose who gets credit',
  'app.loading': 'Loading…',
  'reader.success.tip': 'Includes a {tip} tip',
  'app.home.mineAdminOnly': 'Ask an admin to see your sales and tips.',
  // App-only words for vouchers on a phone (UX spec §13: the share sheet in place of a download)
  'app.voucher.pdf': 'Share or print the voucher',
  'app.voucher.pdfFailed': "We couldn't open the voucher. Please try again.",
  // ── App step 2: card payments (UX spec §13.4, §18.12, §18.17, §18.26, §18.28, §18.35, §23) ──
  // Payment methods (§18.12, §3.19)
  'pay.method.cardReader': 'Card reader',
  'pay.method.link': 'Pay by link or QR code',
  'pay.method.savedCard': 'Card on file',
  'app.howToTap.title': 'How to use Tap to Pay on iPhone',
  'app.sendToReader': 'Send to {reader}',
  'app.web.readers': 'Card readers and printers',
  // The counter reader (§3.19.3; the web's `reader.*`)
  'reader.choose': 'Which reader?',
  'reader.status.online': 'Ready',
  'reader.status.offline': 'Offline',
  'reader.status.busy': 'Busy',
  'reader.sending': 'Sending {amount} to {reader}…',
  'reader.waiting.title': 'Waiting for the card',
  'reader.waiting.body': 'Ask {clientName} to tap, insert or swipe their card on {reader}.',
  'reader.waiting.tip': 'The reader will ask about a tip first.',
  'reader.cancel': 'Cancel',
  'reader.confirming': "The card went through on the reader. We're confirming it with Stripe…",
  'reader.slow': 'Still waiting. If {clientName} has walked away, cancel. If the card was charged, it will show here by itself.',
  'reader.success': 'Paid {amount} by {cardBrand} ending {last4}',
  'reader.success.plain': 'Paid {amount} on the card reader', // (added on the web) no card details came back
  'reader.declined.title': 'Card declined',
  'reader.declined.stillOpen': 'The payment is still open on the reader. Ask {clientName} to try again or use another card.',
  'reader.declined.pin': 'Their bank wants chip and PIN. Ask {clientName} to insert the card and enter their PIN.',
  'reader.movedAway': "{reader} is now registered to another business, so it can't take this payment. Use another reader or send a pay link.",
  'reader.tryAgain': 'Try again',
  'reader.cancelled': 'Payment cancelled. Nothing was taken.',
  'reader.useOther': 'Use another reader',
  'reader.useLink': 'Send a pay link instead',
  'reader.checking': "Checking with the bank. This can take a few minutes. Don't take the payment again.",
  'reader.failed.title': "The payment didn't go through", // (added on the web)
  'reader.none': 'Add a card reader in Settings, Checkout to take cards here.', // (added on the web)
  'err.invalid_state': "This card payment has already gone through, so it can't be cancelled. If it was a mistake, refund it.",
  // Saving a card (§13.4 "Saving a card on the phone", §18.12, §18.28)
  'reader.consent.text':
    'Save this card so {venue} can take payments for your future visits when you agree to them. You can ask them to remove it at any time.',
  'reader.saved': 'Card saved for next time.',
  'reader.notSaved': "{clientName} didn't agree, so the card wasn't saved. The payment went through.",
  'reader.notSaved.wallet':
    "The payment went through, but the card wasn't saved. Phone and watch payments sometimes can't be kept for next time. Ask {clientName} to use their card instead if they'd like it saved.",
  'app.saveCard.handTo': 'Hand the phone to {clientName} so they can choose whether to save their card.',
  'app.saveCard.title': 'Save your card for next time?',
  'app.saveCard.agree': 'Yes, save my card',
  'app.saveCard.decline': 'No thanks',
  'app.saveCard.handBack': 'Thank you. Please hand the phone back.',
  'app.saveCard.ready': 'I have handed it over', // (added) staff's button on the hand-over screen
  // Pay by link or QR code (§3.19.4, §3.29; the web's `link.*`)
  'link.title': 'Pay by link or QR code', // (added on the web)
  'link.amount': 'Amount on this link', // (added on the web)
  'link.tipNote': 'The {client} can add a tip on their phone.',
  'link.allowTip': 'Let them add a tip on their phone', // (added on the web)
  'link.create': 'Create link',
  'link.scan': "Ask {clientName} to scan this with their phone's camera.",
  'link.qrAlt': 'QR code for the pay link', // (added on the web)
  'link.copy': 'Copy link',
  'link.copied': 'Link copied.', // (added on the web)
  'link.share': 'Share link', // (added) the phone's share sheet
  'link.text': 'Text it',
  'link.email': 'Email it',
  'link.text.to': 'Mobile number',
  'link.email.to': 'Email address',
  'link.send': 'Send', // (added on the web)
  'link.sent.text': 'Sent to {phone}.',
  'link.sent.email': 'Sent to {email}.',
  'link.waiting': 'Waiting for {clientName} to pay',
  'link.waitingAmount': 'Waiting for {amount} on a pay link', // (added on the web)
  'link.expires': 'The link works until {time} on {date}.',
  'link.cancel': 'Cancel link',
  'link.cancel.confirm.title': 'Cancel this pay link?',
  'link.cancel.confirm.body': 'The link stops working straight away. Nothing has been paid on it.',
  'link.cancel.confirm.button': 'Cancel link', // (added on the web)
  'link.cancel.keep': 'Keep it', // (added on the web)
  'link.paid': '{clientName} paid {amount}',
  'link.later': 'They can pay later. Park this sale, and it updates by itself when they pay.',
  'link.attemptFailed': 'A card was declined on the link. {clientName} can try another card.',
  'link.list': 'Pay links', // (added on the web)
  'link.status.cancelled': 'Cancelled', // (added on the web)
  'link.status.expired': 'Expired', // (added on the web)
  'link.show': 'Show QR code', // (added on the web)
  'link.back': 'Choose another way to pay',
  'link.close': 'Close', // (added on the web)
  'done.tipLink': 'Send a tip link',
  'link.tipOnly.title': 'Send {clientName} a tip link?',
  'link.tipOnly.body':
    "They've paid in full. If they'd like to leave a tip later, this link lets them choose an amount on their phone. Nothing is charged unless they choose one.",
  'link.tipOnly.send': 'Send tip link',
  'link.tipOnly.sent': 'Tip link sent to {destination}.',
  'link.tipOnly.how': 'How should we send it?', // (added on the web)
  // Card on file (§3.19.5, §4.3, §18.12, §18.17)
  'saved.card': '{brand} ending {last4}, expires {expiry}',
  'saved.consent': 'Saved with permission on {date}, {channel}',
  'saved.channel.reader': 'at the desk',
  'saved.channel.app': 'on the phone at the desk', // (added on the web)
  'saved.channel.online_booking': 'when booking online',
  'saved.channel.shop': 'in the online shop',
  'saved.channel.account': 'in their account',
  'saved.confirm.title': 'Charge {amount} to {brand} ending {last4}?',
  'saved.confirm.body': 'Only charge a saved card when {clientName} has agreed to this payment.',
  'saved.confirm.button': 'Charge card',
  'saved.processing': 'Charging the card…',
  'saved.method': 'Card on file: {brand} ending {last4}', // (added on the web)
  'saved.notCharged': "The card on file wasn't charged", // (added on the web)
  'saved.declined': 'The card was declined. Ask {clientName} to try another card or another way to pay.', // (added on the web)
  'client.cards.title': 'Saved cards',
  'client.cards.remove': 'Remove card',
  'client.cards.remove.title': 'Remove this card?',
  'client.cards.remove.body': "{venue} won't be able to charge it again. {clientName} can save it again next time they pay.",
  'client.cards.empty': 'No saved cards.',
  'client.cards.removed': '{card} removed.', // (added on the web)
  'client.cards.loadFailed': "We couldn't load the saved cards.", // (added on the web)
  // Payouts and fees, for admins (§11.1, §18.26; instant payouts are v1.x)
  'rep.t.payouts': 'Payouts and fees',
  'rep.payout.arrives': 'Arrives',
  'rep.payout.amount': 'Amount',
  'rep.payout.fees': 'Stripe fees',
  'rep.payout.status': 'Status',
  'rep.payout.intro': 'What Stripe is sending to your bank for this period, and the fees it took. Open a payout to see the payments it covered.', // (added on the web)
  'rep.payout.notConnected': 'Connect Stripe in Settings, Payments to see your payouts here.', // (added on the web)
  'rep.payout.none': 'No payouts arrive in this period.', // (added)
  'rep.payout.truncated': 'Showing the first 40 payouts. Choose a shorter period to see the rest.', // (added on the web)
  'rep.payout.feesNotListed': 'Not listed', // (added on the web)
  'rep.payout.show': 'Show payments', // (added on the web)
  'rep.payout.hide': 'Hide', // (added on the web)
  'rep.payout.manual': "This payout was made by hand in Stripe, so Stripe doesn't list what it covered.", // (added on the web)
  'rep.payout.covered': 'What this payout covered', // (added on the web)
  'rep.payout.paidOut': 'Paid out', // (added on the web)
  'rep.payout.status.paid': 'Paid', // (added on the web)
  'rep.payout.status.on_its_way': 'On its way', // (added on the web)
  'rep.payout.status.pending': 'Pending', // (added on the web)
  'rep.payout.status.failed': 'Failed', // (added on the web)
  'rep.payout.status.cancelled': 'Cancelled', // (added on the web)
  // Send to a phone: the app side (§18.35, §23.5)
  'pay.phone.row': "Card, on {staffName}'s phone",
  'err.POS_PAYMENT_CLAIMED': '{staffName} has already taken this payment on their phone.',
  'err.POS_COLLECT_EXPIRED': 'Nobody took this payment in time. Send it again.',
  'err.POS_NO_CARD_DEVICE': 'No phone here can take cards. Send a pay link instead.',
  'app.collect.list.title': 'Waiting for you',
  'app.collect.row': '{amount} for Sale {saleNo}, from {staffName}',
  'app.collect.row.any': 'For anyone',
  'app.collect.row.expires': '{seconds} seconds left to take it',
  'app.collect.title': 'Take {amount}',
  'app.collect.for': 'Sale {saleNo} at {till}, sent by {staffName}',
  'app.collect.client': 'For {clientName}',
  'app.collect.processing': 'Processing',
  'app.collect.done': 'Paid. The desk can see it.',
  'app.collect.declined': 'The card was declined. Try again, or ask for another card.',
  'app.collect.tryAgain': 'Try again',
  'app.collect.insertCard':
    "This card needs to be inserted with a PIN, and a phone can't do that. Send a pay link, or try another card.",
  'app.collect.sendLink': 'Send a pay link',
  'app.collect.otherCard': 'Try another card',
  'app.collect.useCounter': 'Use the card reader at the desk',
  'app.collect.timeout': "The card wasn't tapped within 5 minutes, so this stopped. Nothing was taken.",
  'app.collect.cancelledByDesk': 'The desk cancelled this payment. Nothing was taken.',
  'app.collect.accountLimit':
    "This iPhone has taken Tap to Pay payments for three businesses in the last 24 hours, which is Stripe's limit. Use another phone, or try again later.",
  'app.collect.expired': 'Nobody took this payment in time, so it was cancelled. Nothing was taken.', // (added) phone.expired, as the phone says it
  'app.collect.gone': 'This payment has ended. Nothing more to do here.', // (added) paid, cancelled or failed before this phone took it
  'app.collect.otherVenue': 'This payment is for another business. Switch to it in the app, then open it again.', // (added)
  'app.collect.someone': 'Someone at the desk', // (added) when the sender is not known
  'app.collect.desk': 'the desk', // (added) when the till has no name
  'app.collect.backToSale': 'Open the sale', // (added)
  'app.collect.close': 'Done', // (added)
  // ─── App step 4 (Pass 4) and the Pass LC app step ───────────────────────────
  // §18.5 Products at the till (Pass 4, P4-4), from the web till's deck
  'add.tab.products': 'Products',
  'add.stock.left': '{count} left',
  'add.stock.out': 'Out of stock',
  'add.variant.title': 'Choose an option',
  'add.stock.warnOver': 'The stock count says {count} left. You can still sell it, and the count will go below zero.',
  'add.stock.warnReserved': "The last {count} are set aside for online customers who are checking out or have reserved them. You can still sell it here, and we'll let you know the stock needs sorting out.",
  'scan.added': 'Added {product}',
  'scan.unknown': 'No product has the barcode {barcode}.',
  'scan.unknown.search': 'Search instead',
  'err.stock.none': "{product} is out of stock, and {venue} doesn't sell more than the stock count. Check the count in Stock.",
  'line.chip.stockLow': '{count} left',
  'line.chip.stockNone': 'Stock count below zero',
  'refund.restock': 'Put back in stock',
  'refund.restock.help': 'Tick this if it can be sold again.',
  // §18.19 Products (src/components/retail/copy.ts)
  'prod.title': 'Products',
  'prod.add': 'Add product',
  'prod.readOnly': 'You can look products up here. An admin can let you edit them.',
  'prod.search': 'Search by name, brand, SKU or barcode',
  'prod.filter.archived': 'Archived',
  'prod.filter.low': 'Low stock',
  'prod.use.retail': 'For sale',
  'prod.use.professional': 'For treatments only (backbar)',
  'prod.use.both': 'Both',
  'prod.row.options': '{count} options',
  'prod.row.options.one': '1 option',
  'prod.row.from': 'From {amount}',
  'prod.row.stock': '{count} in stock',
  'prod.row.out': 'Out of stock',
  'prod.row.notTracked': 'Not counted',
  'prod.pill.online': 'Online',
  'prod.pill.backbar': 'Backbar',
  'prod.pill.low': 'Low',
  'prod.pill.archived': 'Archived',
  'prod.empty.title': 'Add your first product',
  'prod.empty.body': 'Add the products you sell, or the ones you use in treatments. You can import a list from Fresha, Phorest or a spreadsheet.',
  'prod.none.filtered': 'No products match these filters.',
  'prod.clearFilters': 'Clear filters',
  'prod.error': "We couldn't load your products.",
  'prod.f.name': 'Name',
  'prod.f.brand': 'Brand',
  'prod.f.category': 'Category',
  'prod.f.description': 'Description',
  'prod.photos.main': 'Main photo',
  'prod.photos.add': 'Add photos',
  'prod.photos.limit': 'You can add up to 8 photos.',
  'prod.photos.tooBig': 'That photo is too big. Choose one under 10 MB.',
  'prod.photos.wrongType': 'Choose a JPG, PNG or WebP photo.',
  'prod.photos.failed': "The photo didn't upload. Please try again.",
  'prod.photos.remove': 'Remove photo',
  'prod.f.use': 'How you use it',
  'prod.f.soldInStore': 'Sell it at the till',
  'prod.f.notOnline': 'Not sold online',
  'prod.f.notOnline.help': 'Keeps this product out of your online shop. Tick it for medicines and alcohol, and anything else you only sell in person.',
  'prod.f.age18': 'Age restricted (18+)',
  'prod.f.age18.help': 'For things like straight razors and loose blades. It stays out of your online shop, and the till reminds your team to check the {client} is 18 or over.',
  'prod.f.vat': 'VAT rate',
  'prod.vat.default': 'Your default for products ({rate})',
  'prod.stock.notTracked': "Stock isn't counted for this option.",
  'prod.save': 'Save product',
  'prod.saved': 'Product saved.',
  'prod.archive': 'Archive product',
  'prod.archive.title': 'Archive {product}?',
  'prod.archive.body': 'It disappears from the till and your shop, and stays in your records and reports. You can unarchive it at any time.',
  'prod.unarchive': 'Unarchive',
  'prod.delete': 'Delete product',
  'prod.delete.title': 'Delete {product}?',
  'prod.delete.body': "This can't be undone. Only products that have never been sold, counted or received can be deleted.",
  'var.makeOptions': 'This product comes in different sizes or shades',
  'var.option': 'Option name',
  'var.sku': 'SKU',
  'var.sku.help': 'Your own stock code. Optional.',
  'var.barcodes': 'Barcodes',
  'var.barcode.add': 'Add barcode',
  'var.barcode.invalid': "That barcode's check digit is wrong. Check it and try again.",
  'var.price': 'Price',
  'var.cost': 'Cost',
  'var.cost.help': 'What one costs you. We update it to the average each time you receive stock.',
  'var.track': 'Count stock',
  'var.reorderLevel': 'Reorder at',
  'var.reorderLevel.help': "We'll tell you when stock gets down to this number.",
  'var.reorderQty': 'Reorder quantity',
  'var.add': 'Add an option',
  'var.archive': 'Archive option',
  // Products words the deck leaves unworded (src/components/retail/products/products-copy.ts)
  'common.unsaved': "You have changes that aren't saved. Leave without saving?",
  'vat.rate.standard': 'Standard (20%)',
  'vat.rate.reduced': 'Reduced (5%)',
  'vat.rate.zero': 'Zero (0%)',
  'vat.rate.exempt': 'Exempt',
  'x.notFound': "We couldn't find that product. It may have been removed, or belong to another venue.",
  'x.addTitle': 'Add product',
  'x.basics': 'Basics',
  'x.photos': 'Photos',
  'x.photosAfterSave': 'Save the product first, then add photos.',
  'x.photosUploading': 'Uploading…',
  'x.use': 'How you use it',
  'x.restrictions': 'Restrictions and product details',
  'x.vat': 'VAT',
  'x.options': 'Options',
  'x.stock': 'Stock',
  'x.none': 'None',
  'x.removeBarcode': 'Remove barcode {barcode}',
  'x.opening': 'Starting count',
  'x.opening.help': 'How many you have now. We record it as opening stock.',
  'x.option.n': 'Option {n}',
  'x.option.remove': 'Remove option',
  'x.price.invalid': 'Enter a price, like 12.50.',
  'x.number.invalid': 'Enter a whole number.',
  'x.name.required': 'Give the product a name.',
  'x.needOption': 'Add at least one option.',
  'x.fixFields': 'Some details need checking. Look for the messages under the fields.',
  'x.deleted': 'Product deleted.',
  'x.archived': 'Product archived.',
  'x.unarchived': 'Product unarchived.',
  'x.archivedNote': 'This product is archived. It is not on the till or in your shop.',
  'x.stock.onHand': 'In stock',
  'x.stock.reserved': 'Held for online orders',
  'x.noCategory': 'No category',
  'x.noBrand': 'No brand',
  'x.leave': 'Leave without saving',
  'x.stay': 'Keep editing',
  // §18.20 Stock and stocktakes (src/components/retail/copy.ts)
  'stock.tab.levels': 'Stock levels',
  'stock.tab.movements': 'Movements',
  'stock.tab.stocktakes': 'Stocktakes',
  'stock.tile.valueCost': 'Stock value at cost',
  'stock.tile.low': 'Low',
  'stock.tile.out': 'Out of stock',
  'stock.filter.all': 'All',
  'stock.filter.low': 'Low',
  'stock.filter.out': 'Out',
  'stock.filter.negative': 'Below zero',
  'stock.col.onHand': 'In stock',
  'stock.col.reserved': 'Held for online orders',
  'stock.col.available': 'Available',
  'stock.col.reorderAt': 'Reorder at',
  'stock.pill.low': 'Low',
  'stock.pill.out': 'Out',
  'stock.pill.negative': 'Below zero',
  'stock.adjust': 'Adjust',
  'stock.history': 'History',
  'stock.empty.title': 'No stock counted yet',
  'stock.empty.body': 'Turn on Count stock for a product option to see it here.',
  'adj.title': 'Adjust stock for {product}',
  'adj.mode.change': 'Add or remove',
  'adj.mode.set': 'Set the count to',
  'adj.reason': 'Reason',
  'adj.reason.adjustment': 'Correcting the count',
  'adj.reason.wastage': 'Wastage',
  'adj.reason.damaged': 'Damaged',
  'adj.reason.expired': 'Expired',
  'adj.reason.theft': 'Lost or stolen',
  'adj.note': 'Note (optional)',
  'adj.preview': 'In stock goes from {from} to {to}.',
  'adj.confirm': 'Save adjustment',
  'adj.saved': 'Stock adjusted.',
  'mov.reason.opening': 'Opening stock',
  'mov.reason.receive': 'Received',
  'mov.reason.sale': 'Sold',
  'mov.reason.refund_restock': 'Put back after a refund',
  'mov.reason.adjustment': 'Count corrected',
  'mov.reason.stocktake': 'Stocktake',
  'mov.reason.wastage': 'Wastage',
  'mov.reason.damaged': 'Damaged',
  'mov.reason.expired': 'Expired',
  'mov.reason.theft': 'Lost or stolen',
  'mov.reason.professional_use': 'Used in treatments',
  'mov.reason.professional_use_reversal': 'Use undone (booking reopened)',
  'mov.reason.transfer_out': 'Moved to another site',
  'mov.reason.transfer_in': 'Moved from another site',
  'mov.reason.import': 'Imported',
  'mov.ref.sale': 'Sale {saleNo}',
  'mov.ref.return': 'Return on Sale {saleNo}',
  'mov.ref.order': 'Order {orderNo}',
  'mov.ref.po': 'Purchase order {poNumber}',
  'mov.ref.stocktake': 'Stocktake {number}',
  'mov.ref.booking': 'Booking on {shortDate}',
  'mov.empty': 'No stock changes in this period.',
  'take.start': 'Start a stocktake',
  'take.status.counting': 'Counting',
  'take.status.review': 'Ready to review',
  'take.status.committed': 'Done',
  'take.status.cancelled': 'Cancelled',
  'take.start.title': 'Start a stocktake',
  'take.name': 'Name',
  'take.name.default': 'Stocktake {date}',
  'take.scope.full': 'Everything',
  'take.scope.partial': 'Only some products',
  'take.start.help': 'You can keep selling while you count. We allow for sales made during the count.',
  'take.start.confirm': 'Start counting',
  'take.progress': '{counted} of {total} counted',
  'take.counters': 'Counting now: {names}',
  'take.scan': 'Scan or search',
  'take.scan.added': '+1 {product}',
  'take.scan.unknown': 'No product has the barcode {barcode}.',
  'take.scan.outOfScope': "{product} isn't part of this stocktake.",
  'take.scan.countAnyway': 'Count it anyway',
  'take.counted': 'Counted: {count}',
  'take.plusOne': '+1',
  'take.setCount': 'Type the count',
  'take.lastBy': 'Last counted by {staffName} at {time}',
  'take.review': 'Review differences',
  'take.cancel': 'Cancel stocktake',
  'take.cancel.title': 'Cancel this stocktake?',
  'take.cancel.body': "The counts so far are thrown away, and your stock doesn't change.",
  'take.col.expected': 'Expected',
  'take.col.counted': 'Counted',
  'take.col.sold': 'Sold during the count',
  'take.col.change': 'Change',
  'take.col.value': 'Value at cost',
  'take.filter.differences': 'Differences only',
  'take.filter.uncounted': 'Not counted',
  'take.variance': 'Difference at cost: {amount}',
  'take.zeroUncounted': 'Count anything not counted as zero',
  'take.zeroUncounted.help': "Use this when you've counted everything. {count} product options weren't counted.",
  'take.zeroUncounted.held': "{count} of these are held for online orders. Their holds stay, and we'll flag them for you to check.",
  'take.backToCount': 'Back to counting',
  'take.commit': 'Update stock',
  'take.commit.title': 'Update stock from this count?',
  'take.commit.body': "{count} product options change, worth {amount} at cost. This can't be undone, but the stocktake stays in your records.",
  'take.done': 'Stock updated. This stocktake is saved in your records.',
  'feat.stock.off.title': 'Stock tracking is off',
  'feat.stock.off.body': 'Turn on Track stock in Settings, Checkout, Features to count your products and get low-stock alerts.',
  'err.stock.belowZero': 'That would take {product} below zero. Check the count, or do a stocktake.',
  // Stock words the deck leaves unworded (src/components/retail/stock/stock-copy.ts)
  'stock.title': 'Stock',
  'stock.search': 'Search by name, brand, SKU or barcode',
  'stock.error': "We couldn't load your stock.",
  'stock.none.filtered': 'Nothing matches this filter.',
  'adj.quantity.change': 'How many to add or remove',
  'adj.quantity.change.help': 'Use a minus sign to take stock away, like -2.',
  'adj.quantity.set': 'The new count',
  'adj.note.help': "Your team sees this note. Don't name a {client} in it.",
  'adj.quantity.whole': 'Enter whole units.',
  'adj.quantity.zero': 'Enter how many to add or remove.',
  'adj.reason.required': 'Choose a reason.',
  'mov.col.after': 'In stock after',
  'mov.error': "We couldn't load the stock changes.",
  'take.name.required': 'Give the stocktake a name.',
  'take.startedBy': '{name}, {date}',
  'take.empty.title': 'No stocktakes yet',
  'take.empty.body': 'A stocktake checks your counts against what is on the shelf.',
  'take.error': "We couldn't load this stocktake.",
  'take.list.error': "We couldn't load your stocktakes.",
  'take.scope.categories': 'Categories',
  'take.scope.brands': 'Brands',
  'take.scope.suppliers': 'Suppliers',
  'take.scope.none': 'None added yet.',
  'take.scope.pickOne': 'Choose at least one category, brand or supplier to count.',
  'take.notCounted': 'Not counted',
  'take.setCount.save': 'Save count',
  'take.scan.lookup': 'Looking that up',
  'take.record.cancelled': 'This stocktake was cancelled, so your stock did not change.',
  'take.record.committed': 'Stock was updated from this count by {name} on {date}.',
  'take.none.filtered': 'Nothing to show with these filters.',
  // §4.3 The client profile: spend and purchases (P4-8)
  'client.stats.spend': 'Lifetime spend',
  'client.stats.average': 'Average spend',
  'client.stats.none': 'Nothing yet',
  'client.purchases.title': 'Purchases',
  'client.purchases.where.till': 'At the desk',
  'client.purchases.where.online': 'Online',
  'client.purchases.empty': 'No products bought yet.',
  // §18.33 Loyalty cards (src/lib/pos/loyalty/copy.ts)
  'loyalty.reward.free': 'a free {serviceName}',
  'loyalty.reward.amount': '{amount} off',
  'loyalty.reward.percent': '{percent}% off',
  'loyalty.card.title': 'Loyalty card',
  'loyalty.card.progress': '{count} of {needed} visits',
  'loyalty.card.reward': 'Reward ready: {rewardText}',
  'loyalty.card.rewardExpires': 'Use by {date}',
  'loyalty.card.noReward': 'No reward waiting yet',
  'loyalty.card.history': 'History',
  'loyalty.card.empty': 'No stamps yet. They get one each day they visit, from {date}.',
  'loyalty.card.paused': 'The loyalty card is paused, so nobody is earning stamps.',
  'loyalty.h.earn': 'Stamp for the visit on {date}',
  'loyalty.h.reverse': 'Stamp taken off, because the visit on {date} is no longer completed',
  'loyalty.h.adjust': '{count} stamps added by {staffName}: {reason}',
  'loyalty.h.adjust.one': '1 stamp added by {staffName}: {reason}',
  'loyalty.h.adjust.remove': '{count} stamps taken off by {staffName}: {reason}',
  'loyalty.h.adjust.remove.one': '1 stamp taken off by {staffName}: {reason}',
  'loyalty.h.spend': 'Card filled, so a reward was earned',
  'loyalty.h.used': 'Reward used on Sale {saleNo}',
  'loyalty.h.expired': 'Reward ran out',
  'loyalty.h.cancelled': 'Reward cancelled, because a stamp was taken off',
  'loyalty.adjust': 'Add or remove stamps',
  'loyalty.adjust.title': 'Change stamps',
  'loyalty.adjust.add': 'Add stamps',
  'loyalty.adjust.remove': 'Remove stamps',
  'loyalty.adjust.count': 'How many',
  'loyalty.adjust.reason': 'Reason',
  'loyalty.adjust.reason.paper': 'Carried over from a paper card',
  'loyalty.adjust.reason.mistake': 'Correcting a mistake',
  'loyalty.adjust.confirm': 'Save',
  'loyalty.adjust.tooMany': 'The card only has {count} stamps.',
  'loyalty.adjust.tooMany.one': 'The card only has 1 stamp.',
  'loyalty.adjust.filled': 'The card is full, so {clientName} has a reward ready: {rewardText}.',
  'loyalty.ready': 'Reward ready',
  'loyalty.apply.title': "{clientName}'s reward",
  'loyalty.apply.body': '{rewardText}. Use it on this sale?',
  'loyalty.apply.confirm': 'Use the reward',
  'loyalty.apply.noService': 'Add {serviceName} to the sale to use this reward.',
  'disc.loyalty': 'Loyalty reward: {rewardText}',
  'err.LOYALTY_REWARD_UNAVAILABLE': 'This reward has already been used, or it has run out.',
  'feat.loyalty.setup': 'Loyalty cards are ready to set up. Choose how many visits fill a card and what the reward is.',
  // §18.34 Commission: my own figures (src/lib/pos/commission/copy.ts)
  'comm.mine.period.today': 'Today',
  'comm.mine.period.week': 'This week',
  'comm.mine.period.month': 'This month',
  'comm.mine.sales': 'Sales credited to you: {amount}',
  'comm.mine.tips': 'Tips: {amount}',
  'comm.mine.commission': 'Commission so far: {amount}',
  'comm.mine.note': 'Worked out from your sales as they stand today. {venue} confirms the final figure when it pays you.',

  // §18.28 The ResNeo app: app step 4 and the Pass LC web rows (UX spec §13.6, §13.8, §18.31)
  'app.tile.stock': 'Products and stock',
  'app.tile.stock.hint': 'Stock levels, stocktakes and deliveries',
  'app.photo.library': 'Choose a photo',
  'app.photo.camera': 'Take a photo',
  'app.photo.permission': 'ResNeo needs your camera to take photos of products and receipts.',
  'app.photo.denied': "Camera access is off. Turn it on in your phone's settings, or choose a photo instead.",
  'app.stocktake.offline': "You're offline. Your counts are saved on this phone and will be sent when you're back online.",
  // Camera scanning, over the air with app step 4 (§13.6), word for word from §18.28.
  'app.scan.title': 'Scan a barcode',
  'app.scan.hint': 'Point the camera at the barcode.',
  'app.scan.torch': 'Torch',
  'app.scan.permission': 'ResNeo needs your camera to scan barcodes.',
  'app.scan.denied': "Camera access is off. Turn it on in your phone's settings to scan, or type the code instead.",
  'app.web.stockSetup': 'Suppliers, labels and stock set-up',
  'app.web.loyalty': 'Loyalty card set-up',
  'app.web.commission': 'Commission rates and report',
  // ── App step 3: till sessions, cash-up and end of day (UX spec §7, §13.5, §18.21) ──
  // Word for word from the web's `src/lib/pos/till/copy.ts`.
  'till.tab.till': 'Till',
  'till.tab.eod': 'End of day',
  'session.chip.open': 'Till open',
  'session.chip.closed': 'Till closed',
  'session.closed.title': '{till} is closed',
  'session.closed.body': 'Open it with your float to start taking cash.',
  'session.open': 'Open the till',
  'session.openSince': 'Opened by {staffName} at {time} with a {amount} float',
  'session.paidIn': 'Paid in',
  'session.paidOut': 'Paid out',
  'session.safeDrop': 'Safe drop',
  'session.tipsOut': 'Tips paid out',
  'session.xReport': 'X report',
  'session.close': 'Close the till',
  'session.otherTills': 'Other tills',
  'session.leftOpen': "{till} has been open since {date}. Close it to count that day's cash before starting today.",
  'session.error': "We couldn't load the till.",
  'session.open.title': 'Open {till}',
  'session.float': 'Float in the drawer',
  'session.float.fromLast': 'Left in the drawer last time: {amount}',
  'session.countByDenom': 'Count notes and coins',
  'session.open.confirm': 'Open till',
  'session.opened': '{till} is open.',
  'session.openNow': 'Open the till',
  'session.open.refundOnly': 'Your plan needs attention, so this session can only be used to give a cash refund.',
  'move.kind.paid_in': 'Paid in',
  'move.kind.paid_out': 'Paid out',
  'move.kind.safe_drop': 'Safe drop',
  'move.kind.tips_paid_out': 'Tips paid out',
  'move.kind.no_sale': 'Drawer opened',
  'move.in.title': 'Paid in',
  'move.out.title': 'Paid out',
  'move.category': 'What for',
  'move.in.bank': 'Change from the bank',
  'move.in.float': 'Float (change from the safe)',
  'move.in.other': 'Something else',
  'move.out.petty': 'Petty cash purchase',
  'move.out.supplier': 'Supplier paid in cash',
  'move.out.expenses': 'Staff expenses',
  'move.out.other': 'Something else',
  'move.note': 'Note',
  'move.photo': 'Add a photo of the receipt',
  'move.in.confirm': 'Record paid in',
  'move.out.confirm': 'Record paid out',
  'move.drop.title': 'Safe drop',
  'move.drop.help': 'Take cash out of the drawer to keep it safe during the day.',
  'move.drop.confirm': 'Record safe drop',
  'move.tips.title': 'Tips paid out',
  'move.tips.help': "For cash tips your team takes from the drawer. It's linked to their tip records.",
  'move.tips.confirm': 'Record {amount} paid out',
  'close.title': 'Close {till}',
  'close.count.body': 'Count all the cash in the drawer.',
  'close.blind': "You'll see how it compares once you've counted.",
  'close.total': 'Total counted',
  'close.next': 'Next',
  'close.expected': 'Expected {expected}. Counted {counted}.',
  'close.expected.before': 'Expected in the drawer: {expected}',
  'close.balanced': 'It balances.',
  'close.over': '{amount} over',
  'close.short': '{amount} short',
  'close.needsReason': "The count doesn't match what we expected. Please say what might explain it.",
  'close.reason': 'What might explain the difference?',
  'close.recount': 'Count again',
  'close.bank': 'Cash going to the bank',
  'close.floatLeft': 'Float left in the drawer',
  'close.mismatch': 'These need to add up to the {counted} you counted.',
  'close.legacyCash': 'Cash from older app versions and desk deposits: {amount}',
  'close.confirm': 'Close till',
  'z.title': 'Z report',
  'z.xTitle': 'X report',
  'z.xWatermark': 'X report: the till is still open',
  'z.opened': 'Opened',
  'z.closed': 'Closed',
  'z.sales': 'Sales',
  'z.byMethod': 'Takings by method',
  'z.refunds': 'Refunds',
  'z.discounts': 'Discounts',
  'z.voids': 'Voids',
  'z.tips': 'Tips',
  'z.tipsCard': 'On cards',
  'z.tipsCash': 'In cash',
  'z.tipsOut': 'Paid out from the drawer',
  'z.cash': 'Cash',
  'z.float': 'Float',
  'z.cashSales': 'Cash sales',
  'z.cashTips': 'Cash tips received',
  'z.legacyCash': 'Older app and desk deposits',
  'z.cashRefunds': 'Cash refunds',
  'z.paidIn': 'Paid in',
  'z.paidOut': 'Paid out',
  'z.drops': 'Safe drops',
  'z.expected': 'Expected',
  'z.counted': 'Counted',
  'z.difference': 'Difference',
  'z.reason': 'Reason',
  'z.toBank': 'To bank',
  'z.floatLeft': 'Float left',
  'z.email': 'Email to admins',
  'eod.date': 'Day',
  'eod.tile.takings': 'Taken',
  'eod.tile.card': 'Card',
  'eod.tile.cash': 'Cash',
  'eod.tile.other': 'Other',
  'eod.tills': 'Tills',
  'eod.deposits': 'Deposits and no-show fees',
  'eod.tips': 'Tips by person',
  'eod.refunds': 'Refunds',
  'eod.ordersWaiting': 'Online orders waiting',
  'eod.cashOutside': 'Cash outside a till session',
  'eod.cashOutside.help':
    "Cash taken in an older version of the ResNeo app while no till was open. It isn't in any till's expected cash, so put it in the drawer or the safe and note where it went.",
  'denom.note': '{value} notes',
  'denom.coin': '{value} coins',
  'denom.bagged': 'Bagged coins',
  'denom.total': 'Total',
  'home.till.open': '{till} is open, since {time}.',
  'home.till.closed': '{till} is closed. Open it before you take cash.',
  'home.till.leftOpen': '{till} has been open since {date}. Close it to count the cash.',
  'err.POS_TILL_SESSION_REQUIRED': 'Open the till before taking or giving back cash.',
  'err.POS_SESSION_ALREADY_OPEN': '{till} is already open, so you can carry on with that session.',
  'err.POS_VARIANCE_REASON_REQUIRED': 'The count is {difference} out, so please say why before closing.',
  'push.pref.pos_cash_up_reminder': 'Cash-up reminders',
  'push.cashUp.title': 'Time to cash up',
  'push.cashUp.body': 'The {till} till is still open. Close it to finish the day.',
  // The app's own words for app step 3, where the deck has none (a phone shares the PDF, §13.5).
  'app.till.title': 'Till and cash-up', // (added) the Till screen's title
  'app.till.open': 'Open the till screen', // (added) the Till card's button on Checkout
  'app.till.moves': 'Today in the drawer', // (added) the movements list
  'app.till.moves.none': 'Nothing paid in or out yet.', // (added)
  'app.till.moveBy': '{time}, by {staffName}', // (added) one movement's time and who
  'app.till.amount': 'Amount', // (added)
  'app.till.photo.added': 'Receipt photo added', // (added)
  'app.till.photo.remove': 'Remove the photo', // (added)
  'app.till.photo.failed': "We couldn't add that photo. Please try again.", // (added)
  'app.till.photo.view': 'Receipt photo', // (added) a movement's photo thumbnail
  'app.till.recorded': 'Recorded.', // (added)
  'app.till.tips.none': 'Nobody has cash tips waiting to be paid.', // (added)
  'app.till.tips.unpaid': '{amount} to pay', // (added)
  'app.till.report.title': '{report}: {till}', // (added) "X report: Front desk"
  'app.till.report.failed': "We couldn't open the report. Please try again.", // (added)
  'app.till.report.emailed': 'Z report emailed to {count} admins.', // (added)
  'app.till.report.emailed.one': 'Z report emailed to 1 admin.', // (added)
  'app.till.report.totalTaken': 'Total taken', // (added) as on the web's printed report
  'app.till.report.tipsPaidOut': 'Tips paid out', // (added) as on the web's printed report
  'app.till.report.hidden': 'Ask an admin to see the cash count.', // (added) expected cash hidden
  'app.till.chooseTill': 'Which till are you opening?', // (added) several tills, from the cash payment
  'app.till.closed.done': '{till} is closed.', // (added)
  'app.till.eod.open': 'See the end of day', // (added) admins and see_expected_cash
  'app.till.eod.prev': 'Day before', // (added)
  'app.till.eod.next': 'Day after', // (added)
  'app.till.eod.error': "We couldn't load the end of day.", // (added)
  'app.till.eod.tillOpen': '{till} is still open.', // (added) a till not yet counted that day
  'app.till.eod.tillRow': 'Counted {counted}, {difference}', // (added)
  'app.till.eod.tillRowExpected': 'Counted {counted}, expected {expected}, {difference}', // (added)
  'app.till.eod.depositsRow': 'Deposits {deposits}. No-show and late fees {fees}.', // (added)
  'app.till.eod.none': 'Nothing yet.', // (added)
  'app.till.eod.cashRow': '{amount} at {time}, by {staffName}', // (added)
  'app.till.otherVenue': 'This till is at another business. Switch to it in the app, then open it again.', // (added) a cash-up push for another venue
  'app.till.notCounting': "This venue doesn't count cash in till sessions. An admin can turn it on in Settings, Checkout, on the web.", // (added)
  // ── App step 4b: suppliers, purchase orders and Use stock (UX spec §6.12 to §6.14, §18.20) ──
  // Word for word from the web's `src/components/retail/stock/purchasing-copy.ts` and
  // `src/components/retail/copy.ts` (the `sup.*` ids).
  'po.new': 'New order',
  'po.status.draft': 'Draft',
  'po.status.sent': 'Sent',
  'po.status.part_received': 'Part received',
  'po.status.received': 'Received',
  'po.status.cancelled': 'Cancelled',
  'po.empty.title': 'No purchase orders yet',
  'po.empty.body': 'Start one here, or from low stock with Suggest an order.',
  'po.suggest': 'Suggest an order',
  'po.suggest.help': 'Adds everything from {supplier} at or below its reorder level, topped up in whole packs.',
  'po.suggest.none': 'Nothing from {supplier} is low right now.',
  'po.addLine': 'Add a product',
  'po.col.qty': 'Quantity',
  'po.col.cost': 'Unit cost',
  'po.col.total': 'Total',
  'po.expected': 'Expected on',
  'po.notes': 'Notes for the supplier',
  'po.minOrder': "{supplier}'s minimum order is {amount}.",
  'po.send': 'Send to supplier',
  'po.send.title': 'Email this order to {supplier}?',
  'po.send.body': "We'll email a PDF to {email} from {venue}, and replies will go to {replyTo}.",
  'po.cancel': 'Cancel order',
  'po.cancel.title': 'Cancel purchase order {poNumber}?',
  'po.cancel.body': "It stays in your records as cancelled. If you've already sent it, tell {supplier} yourself.",
  'po.noEmail': 'Add an email address for {supplier} to send orders from here.',
  'po.receive': 'Receive delivery',
  'po.receive.scan': 'Scan items as you unpack them',
  'po.receive.qty': 'Received now',
  'po.receive.cost': 'Unit cost',
  'po.receive.ref': 'Delivery note reference (optional)',
  'po.receive.extra': "Add something that wasn't ordered",
  'po.receive.confirm': 'Add {count} items to stock',
  'po.receive.confirm.one': 'Add 1 item to stock',
  'po.receive.done': '{count} items added to stock.',
  'po.receive.done.one': '1 item added to stock.',
  'use.open': 'Record products used',
  'use.title': 'Record products used',
  'use.qty': 'How many',
  'use.booking': 'For a booking (optional)',
  'use.confirm': 'Record use',
  'use.saved': 'Recorded. Stock is updated.',
  'bk.useStock': 'Record products used',
  'po.title': 'Purchase order {poNumber}',
  'po.filter.all': 'All',
  'po.filter.open': 'Open',
  'po.filter.received': 'Received',
  'po.filter.cancelled': 'Cancelled',
  'po.list.error': "We couldn't load your purchase orders.",
  'po.error': "We couldn't load this purchase order.",
  'po.new.title': 'New order',
  'po.new.supplier': 'Supplier',
  'po.new.blank': 'Start an empty order',
  'po.lines.empty': 'No products on this order yet. Add a product, or let us suggest an order.',
  'po.line.remove': 'Remove {product}',
  'po.line.gone': 'This product has been deleted.',
  'po.line.added': 'Added at delivery',
  'po.saved': 'Order saved.',
  'po.unsaved': 'You have changes that are not saved yet.',
  'po.suggest.added': 'Added {count} products from {supplier}.',
  'po.suggest.added.one': 'Added 1 product from {supplier}.',
  'po.sent.toast': 'Order emailed to {supplier}.',
  'po.sentTo': 'Sent to {email} on {date}',
  'po.cancelled.toast': 'Order cancelled.',
  'po.cancelled.note': 'Cancelled on {date}.',
  'po.received.note': 'Received in full on {date}.',
  'po.total': 'Total: {amount}',
  'po.qty.invalid': 'Enter a quantity of 1 or more for {product}.',
  'po.cost.invalid': 'Enter a cost like 4.50 for {product}.',
  'po.search': 'Search by name, SKU or barcode',
  'po.search.none': 'No counted products match. Turn on Count stock for a product to order it.',
  'po.search.add': 'Add',
  'po.readOnly': 'An admin can let you draft and send orders. You can still receive deliveries.',
  'po.receipts.title': 'Deliveries',
  'po.receipts.row': '{count} items, {amount}, by {name} on {date}',
  'po.receipts.row.one': '1 item, {amount}, by {name} on {date}',
  'po.receipts.ref': 'Delivery note {ref}',
  'po.receive.title': 'Receive delivery for order {poNumber}',
  'po.receive.ordered': '{received} of {ordered} received',
  'po.receive.scan.added': '+1 {product}',
  'po.receive.scan.unknown': 'No product has the barcode {barcode}.',
  'po.receive.scan.notOnOrder': "{product} isn't on this order. Add it as something that wasn't ordered?",
  'po.receive.scan.addIt': 'Add it',
  'po.receive.over': "That's {count} more than you ordered. We'll still add it to stock.",
  'po.receive.qty.invalid': 'Enter how many arrived, as a whole number.',
  'po.receive.nothing': 'Enter how many arrived for at least one item.',
  'po.receive.fill': 'Everything arrived',
  'use.product': 'Product',
  'use.product.choose': 'Search for a product used in treatments',
  'use.product.none':
    'No products used in treatments match. In Products, set How you use it to For treatments only, or Both.',
  'use.product.required': 'Choose a product.',
  'use.qty.invalid': 'Enter how many you used, as a whole number.',
  'use.inStock': '{count} in stock',
  'use.booking.none': 'Not for a booking',
  'use.note': 'Note (optional)',
  'use.help': 'Record products you use on clients, like colour and developer, so your stock stays right.',
  'sup.empty.title': 'No suppliers yet',
  'sup.empty.body': 'Add the companies you buy from, so you can order from them in a couple of taps.',
  'sup.f.contact': 'Contact name',
  'sup.f.email': 'Email for orders',
  'sup.f.phone': 'Phone',
  'sup.f.account': 'Your account number with them',
  'sup.f.minOrder': 'Minimum order',
  'sup.col.leadTime': 'Delivery time',
  'sup.leadTime.days': '{count} days',
  'sup.leadTime.days.one': '1 day',
  'sup.error': "We couldn't load your suppliers.",
  // The app's own words for app step 4b, where the deck has none.
  'app.po.tab': 'Orders', // (added) the purchase orders tab on Products and stock
  'app.po.suppliers': 'Suppliers', // (added) the suppliers list
  'app.po.suppliers.web': 'Suppliers are added and changed on the web.', // (added)
  'app.po.noSuppliers': 'Add the companies you buy from on the web first, then order from them here.', // (added)
  'app.po.row': 'Order {poNumber}', // (added)
  'app.po.units': '{received} of {ordered} items received', // (added)
  'app.po.expected': 'Expected {date}', // (added)
  'app.po.setExpected': 'Add a date', // (added)
  'app.po.clearExpected': 'No date', // (added)
  'app.po.save': 'Save order', // (added)
  'app.po.stale': 'Someone else changed this order, so we have loaded the latest version. Check it, then carry on.', // (added)
  'app.po.pdfFailed': "We couldn't open the order. Please try again.", // (added)
  'app.po.chooseSupplier': 'Choose who you are ordering from.', // (added)
  'app.po.over': 'Over by {count}', // (added) a line received beyond what was ordered
  'app.po.extraRemove': 'Remove', // (added)
  'app.use.forBooking': '{time}, {client}', // (added) a booking in the Use stock picker
  // ── App step 5: online orders (UX spec §8, §13.7, §18.22, §18.28) ──
  // Word for word from the web's `src/lib/shop/copy.ts`; v1.x and Pass 6b/6c ids are left out.
  'app.tile.orders': 'Orders',
  'app.tile.orders.hint': 'Online orders to prepare, send or hand over',
  'app.scan.pickup': 'Scan their pickup code',
  'app.sound.orders': 'Order alert sound',
  'app.web.shop': 'Online shop settings',
  'nav.orders.badgeSr': '{count} new orders',
  'push.pref.shop_order_new': 'New online orders',
  'ord.title': 'Orders',
  'ord.subtitle': 'Orders from your online shop.',
  'ord.tab.todo': 'To do',
  'ord.tab.ready': 'Ready to collect',
  'ord.tab.sent': 'Sent',
  'ord.tab.done': 'Done',
  'ord.tab.cancelled': 'Cancelled',
  'ord.tab.all': 'All',
  'ord.search': 'Search by order number, name or email',
  'ord.lookup': 'Pickup code',
  'ord.lookup.find': 'Find order',
  'ord.lookup.none': 'No order has that pickup code.',
  'ord.row.number': 'Order {orderNo}',
  'ord.row.items': '{count} items',
  'ord.row.items.one': '1 item',
  'ord.row.placed': 'Placed {relative}',
  'ord.type.collection': 'Collection',
  'ord.type.delivery': 'Delivery',
  'ord.status.new': 'New',
  'ord.status.preparing': 'Preparing',
  'ord.status.ready': 'Ready to collect',
  'ord.status.collected': 'Collected',
  'ord.status.dispatched': 'Dispatched',
  'ord.status.delivered': 'Delivered',
  'ord.status.cancelled': 'Cancelled',
  'ord.flag.pastHold': 'Not collected by {shortDate}',
  'ord.flag.return': 'Return recorded',
  'ord.flag.refundDue': 'Refund due by {shortDate}',
  'ord.flag.refunded': 'Refunded',
  'ord.flag.partRefunded': 'Part refunded',
  'ord.empty.title': 'No orders yet',
  'ord.empty.body': 'When someone buys from your online shop, their order appears here and we email you.',
  'ord.empty.todo': 'Nothing to prepare right now.',
  'ord.empty.filtered': 'No orders match.',
  'ord.error': "We couldn't load your orders.",
  'ord.denied.title': 'Orders are not open to you',
  'ord.denied.body': 'Ask an admin at {venue} to let you manage online orders.',
  'ord.loadMore': 'Show more',
  'ord.detail.title': 'Order {orderNo}',
  'ord.detail.placed': 'Placed {date} at {time}',
  'ord.detail.items': 'Items',
  'ord.detail.customer': 'Customer',
  'ord.detail.fulfilment': 'Collection or delivery',
  'ord.detail.payments': 'Payments and refunds',
  'ord.detail.messages': 'Messages',
  'ord.detail.timeline': 'Timeline',
  'ord.detail.returns': 'Returns',
  'ord.detail.subtotal': 'Subtotal',
  'ord.detail.delivery': 'Delivery',
  'ord.detail.total': 'Total',
  'ord.detail.vat': 'Includes VAT of {amount}',
  'ord.detail.pickupCode': 'Pickup code {pickupCode}',
  'ord.detail.collectFrom': 'Collect from {venue}',
  'ord.detail.deliverTo': 'Deliver to',
  'ord.detail.tracking': '{carrier}, tracking {trackingNumber}',
  'ord.detail.trackingNone': 'Sent with {carrier}, no tracking number',
  'ord.detail.track': 'Track parcel',
  'ord.detail.paid': 'Paid {amount} by card on {date}',
  'ord.detail.refund': 'Refunded {amount} on {date}',
  'ord.detail.refundPending': 'Refund of {amount} processing',
  'ord.detail.noMessages': 'No messages sent yet.',
  'ord.detail.notFound': "We can't find that order.",
  'ord.customer.marketing': 'Happy to get marketing emails',
  'ord.customer.noMarketing': 'No marketing emails',
  'ord.customer.profile': 'Open their profile',
  'ord.tl.placed': 'Order placed',
  'ord.tl.paid': 'Paid {amount}',
  'ord.tl.preparing': 'Preparing, by {staffName}',
  'ord.tl.ready': 'Marked ready, by {staffName}',
  'ord.tl.collected': 'Collected',
  'ord.tl.collectedNoCode': 'Collected without a pickup code, by {staffName}',
  'ord.tl.dispatched': 'Dispatched with {carrier}',
  'ord.tl.dispatchedNoCarrier': 'Dispatched',
  'ord.tl.tracking': 'Tracking changed, by {staffName}',
  'ord.tl.delivered': 'Delivered',
  'ord.tl.cancelled': 'Cancelled by {staffName}: {reason}',
  'ord.tl.refunded': 'Refunded {amount}',
  'ord.tl.returnRecorded': 'Return recorded, by {staffName}',
  'ord.tl.returnReceived': 'Returned items received',
  'ord.tl.returnEvidence': 'Proof of sending received',
  'ord.action.preparing': 'Start preparing',
  'ord.action.ready': 'Mark ready to collect',
  'ord.action.dispatch': 'Mark dispatched',
  'ord.action.collected': 'Mark collected',
  'ord.action.delivered': 'Mark delivered',
  'ord.action.editTracking': 'Change tracking details',
  'ord.action.cancelRefund': 'Cancel and refund',
  'ord.action.refund': 'Refund or return',
  'ord.action.packingSlip': 'Print packing slip',
  'ord.ready.confirm.title': 'Mark Order {orderNo} ready to collect?',
  'ord.ready.confirm.body': "We'll tell {customerName} it's ready, with their pickup code.",
  'ord.cancel.title': 'Cancel Order {orderNo} and refund {amount}?',
  'ord.cancel.body': "We'll refund the full amount to their card, put the items back in stock and email them.",
  'ord.cancel.reason': 'Reason',
  'ord.cancel.reason.stock': 'Out of stock',
  'ord.cancel.reason.customer': 'The customer asked to cancel',
  'ord.cancel.reason.notCollected': 'Not collected',
  'ord.cancel.reason.other': 'Other',
  'ord.cancel.confirm': 'Cancel and refund',
  'ord.cancel.keep': 'Keep the order',
  'ord.done.cancelled': 'Order {orderNo} cancelled and refunded.',
  'ord.done.moved': 'Order {orderNo} is now {status}.',
  'pickup.title': 'Check their pickup code',
  'pickup.body': 'Ask for the six-character code in their confirmation email or text.',
  'pickup.code': 'Pickup code',
  'pickup.confirm': 'Confirm collection',
  'pickup.noCode': "They don't have the code",
  'pickup.noCode.body': 'Check their name matches {customerName}, and ask for the email address they ordered with.',
  'pickup.noCode.checked': "I've checked who they are",
  'pickup.confirmWithout': 'Mark collected without a code',
  'dispatch.title': 'Add tracking details',
  'dispatch.carrier': 'Carrier',
  'dispatch.carrier.royalMail': 'Royal Mail',
  'dispatch.carrier.parcelforce': 'Parcelforce',
  'dispatch.carrier.dpd': 'DPD',
  'dispatch.carrier.evri': 'Evri',
  'dispatch.carrier.dhl': 'DHL',
  'dispatch.carrier.ups': 'UPS',
  'dispatch.carrier.other': 'Another carrier',
  'dispatch.carrier.otherName': 'Carrier name',
  'dispatch.tracking': 'Tracking number',
  'dispatch.url': 'Tracking link',
  'dispatch.url.invalid': 'Use a full link that starts with https://',
  'dispatch.note': "We'll email {customerName} with these details.",
  'dispatch.noTracking': "Without a tracking number, {customerName} can't follow their parcel. You can still mark it dispatched.",
  'dispatch.confirm': 'Mark dispatched',
  'dispatch.update': 'Save tracking details',
  'ret.record': 'Record a return',
  'ret.record.title': 'Record a return for Order {orderNo}',
  'ret.record.body': 'Choose what the customer is sending back or bringing in, and why.',
  'ret.record.reason': 'Reason',
  'ret.record.reason.changedMind': 'Changed their mind',
  'ret.record.reason.faulty': 'Faulty or damaged',
  'ret.record.reason.wrong': 'Wrong item sent',
  'ret.record.reason.other': 'Something else',
  'ret.record.note': 'Note (optional)',
  'ret.record.confirm': 'Record return',
  'ret.card.title': 'Return recorded on {date}',
  'ret.refund': 'Refund these items',
  'ret.received': 'Goods received',
  'ret.receivedOn': 'Goods received on {date}',
  'ret.dueBy': 'Refund due by {date}',
  'ret.refunded': 'Refunded',
  'ret.evidence': 'Proof of sending received',
  'ret.evidenceOn': 'Proof of sending received on {date}',
  'ret.evidence.title': 'Record proof of sending?',
  'ret.evidence.body':
    "Do this when the customer sends you proof they've posted the items, like a postage receipt. The refund is then due within 14 days, even if the items haven't arrived yet.",
  'ord.refund.title': 'Refund Order {orderNo}', // the web shop deck's `refund.title` (the till's is a sale's)
  'refund.dest.card': 'the card they paid with',
  'refund.nothing': 'Choose at least one item to refund.',
  'refund.windowClosed': 'The return window for this order ended on {date}.',
  'refund.faultyWarning':
    "Only refund after the window if the item is faulty or not as described. Customers' rights for faulty goods last longer.",
  'sstatus.pickup.holdUntil': "We'll keep it for you until {date}.",
  // The app's own words for app step 5, where the deck has none. The slip is a PDF for the share
  // sheet; a server without the PDF route opens the web page instead.
  'app.ord.slip.web': 'The packing slip opens on the web, where you can print it.', // (added)
  'app.ord.slip.failed': "We couldn't get the packing slip. Check your connection and try again.", // (added)
  'app.ord.otherVenue': 'This order is at another business. Switch to it in the app, then open it again.', // (added)
  'app.ord.badge': '{count} new', // (added) the Orders tile's count
  // The app's own words for app step 4, where the deck has none.
  'app.stock.more': 'Show more', // (added) the next page of a list
  'app.stock.option': 'Option', // (added) the option picker's label on a stock row
  'app.stock.saved': 'Saved.', // (added)
  'app.stock.stockSection': 'In stock: {onHand}. Available: {available}.', // (added) one option's stock in the editor
  'app.stock.historyTitle': 'History of {product}', // (added) the movement history sheet
  'app.stock.historyAll': 'Stock changes', // (added) the history of every product
  'app.stock.who': 'By {staffName}', // (added)
  'app.stocktake.pending': 'Counts waiting to send: {count}', // (added) the draft kept on the phone
  'app.stocktake.sendNow': 'Send them now', // (added)
  'app.stocktake.waiting': 'Waiting to send', // (added) a row counted while offline
  'app.loyalty.choose': 'Choose a reward', // (added) two rewards waiting
  'app.mine.error': "We couldn't load your sales and tips.", // (added)
  'app.scan.allow': 'Turn on the camera', // (added) asks for the camera from the scanner
  'app.scan.settings': 'Open settings', // (added) camera access was turned off
  'app.scan.done': 'Done', // (added) closes the camera after scanning several codes
  'app.scan.cameraFailed': "The camera didn't start. Close this and try again, or type the code instead.", // (added)
} as const;

export type PosCopyId = keyof typeof POS_COPY;

export type CopyVars = Record<string, string | number>;

/** Fills `{name}` placeholders. Unknown placeholders are left as they are, so a test can spot them. */
export function fillCopy(template: string, vars: CopyVars = {}): string {
  return template.replace(/\{(\w+)\}/g, (whole, key: string) =>
    Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : whole,
  );
}

/** One string from the deck, filled. */
export function posCopy(id: PosCopyId, vars: CopyVars = {}): string {
  // "1 item", not "1 items": a count of one uses the `<id>.one` wording when there is one.
  const one = `${id}.one`;
  if (Number(vars.count) === 1 && one in POS_COPY) return fillCopy(POS_COPY[one as PosCopyId], vars);
  return fillCopy(POS_COPY[id], vars);
}

/** "client" becomes "Client". */
export function capitalise(word: string): string {
  return word ? word.charAt(0).toUpperCase() + word.slice(1) : word;
}

export type PosT = (id: PosCopyId, vars?: CopyVars) => string;

/** A copy function with the venue's client word filled in (`{client}`, `{Client}`). */
export function posCopyFor(clientWord: string): PosT {
  const lower = (clientWord || 'client').toLowerCase();
  return (id, vars = {}) => posCopy(id, { client: lower, Client: capitalise(lower), ...vars });
}
