import { fillCopy, type CopyVars } from '@/lib/pos/copy';

/**
 * The words of Reports' POS tabs in the app: Takings, Sales, Vouchers and Commission, their date
 * range card, their exports, the voucher sheet, adding and importing vouchers. Kept in step with
 * the web's own words, string for string, where the web has them:
 *
 * - src/app/dashboard/reports/{pos-report-ui,TakingsSection,SalesSection,SalesProductSections,
 *   CashUpsSection,PayoutsSection,VouchersSection,AllVouchersCard,CommissionSection,
 *   StaffPosReportsPanel}.tsx
 * - src/lib/reports/pos-reports.ts (labels), src/lib/reports/sales-products.ts
 * - src/lib/pos/commission/copy.ts (`rep.c.*`)
 * - src/components/pos/vouchers/voucher-copy.ts (`rep.v.*`, `vadd.*`, `vimp.*`, `vch.*`)
 *
 * The house rules apply (CLAUDE.md): no em-dash, straight apostrophes, plain second person, and
 * nothing that singles out one country.
 */
export const REPORTS_COPY = {
  // ─── Tabs and access ──────────────────────────────────────────────────────
  'tab.takings': 'Takings',
  'tab.sales': 'Sales',
  'tab.vouchers': 'Vouchers',
  'tab.commission': 'Commission',
  'staff.ask': 'Ask an admin if you need to see the takings and sales reports.',
  'staff.loading': 'Loading reports...',

  // ─── The range card (pos-report-ui.tsx) ───────────────────────────────────
  'rng.range': 'Range',
  'rng.showBy': 'Show by',
  'rng.choose': 'Choose dates',
  'rng.from': 'From',
  'rng.to': 'To',
  'rng.apply': 'Apply',
  'rng.loading': 'Loading...',
  'rng.endBeforeStart': 'The end date must not be before the start date.',
  'rng.tooLong': 'Choose a range of 400 days or less.',
  'preset.today': 'Today',
  'preset.yesterday': 'Yesterday',
  'preset.this-week': 'This week',
  'preset.last-week': 'Last week',
  'preset.this-month': 'This month',
  'preset.last-month': 'Last month',
  'grain.day': 'Day',
  'grain.week': 'Week',
  'grain.month': 'Month',
  'grain.title.day': 'By day',
  'grain.title.week': 'By week',
  'grain.title.month': 'By month',

  // ─── Shared report parts ──────────────────────────────────────────────────
  'rep.empty': 'Nothing to show for this period.',
  'rep.error': "We couldn't load this report.",
  'rep.tryAgain': 'Try again',
  'rep.export': 'Export CSV',
  'rep.exportLabel': 'Export {title} as CSV',
  'rep.fileFailed': "We couldn't make that file. Please try again.",
  'rep.total': 'Total',
  'rep.period': 'Period',
  'rep.teamMember': 'Team member',
  'rep.quantity': 'Quantity',
  'rep.discounts': 'Discounts',
  'rep.sales': 'Sales',
  'rep.refunds': 'Refunds',
  'rep.amount': 'Amount',
  'rep.category': 'Category',
  'rep.noCategory': 'No category',
  'rep.product': 'Product',
  'rep.day': 'Day',
  'rep.date': 'Date',
  'rep.reason': 'Reason',
  'rep.close': 'Close',

  // ─── Takings (TakingsSection.tsx) ─────────────────────────────────────────
  'tk.help': "Money in and out, on the day it moved. A deposit paid online on Monday for Friday's appointment counts on Monday.",
  'tk.title': 'Takings, {range}',
  'tk.paymentsIn': 'Payments in',
  'tk.refundsOut': 'Refunds out',
  'tk.net': 'Net takings',
  'tk.tips': 'Tips',
  'tk.disputesSub': 'Disputes {amount}',
  'tk.byMethod': 'By payment method',
  'tk.method': 'Method',
  'tk.bySource': 'By where it came from',
  'tk.source': 'Source',
  'tk.byPerson': 'By who took the payment',
  'tk.refundsTitle': 'Refunds and reasons',
  'tk.refund': 'Refund',
  'tk.tipsRefunded': 'Tips refunded',
  'tk.disputes': 'Disputes',
  'tk.opened': 'Opened',
  'tk.status': 'Status',
  'tk.disputed': 'Disputed',
  'tk.moved': 'Moved in this period',
  'tk.evidenceDue': 'Evidence due by',
  'tk.tipsByPerson': 'Tips by person',
  'tk.tipsReceived': 'Tips received',
  'tk.paidOut': 'Paid out',
  'tk.stillToPay': 'Still to pay',
  'tk.tipRecords.help': 'One row per person per month, with every tip received and shared. Keep these records for at least three years.',
  'tk.tipRecords.button': 'Download tip records',
  'tk.vat': 'VAT by rate',
  'tk.vat.help': 'Worked out from completed sales. Deposits and fees kept after cancellations are listed separately for your accountant.',
  'tk.vat.rate': 'Rate',
  'tk.vat.salesVat': 'VAT on sales',
  'tk.vat.refundsVat': 'VAT on refunds',
  'tk.vat.net': 'Net VAT',
  'tk.vat.depositsTaken': 'Deposits taken',
  'tk.vat.depositsRefunded': 'Deposits refunded',
  'tk.vat.depositsKept': 'Deposits kept after a cancellation or no-show',
  'tk.vat.feesCharged': 'No-show and late cancellation fees charged',
  'tk.vat.feesRefunded': 'Fees refunded',

  // CSV labels for the share sheet title (the web's download labels).
  'csv.takings': 'Takings',
  'csv.takings.byMethod': 'Takings by payment method',
  'csv.takings.bySource': 'Takings by source',
  'csv.takings.byPeriod': 'Takings by period',
  'csv.takings.byPerson': 'Takings by person',
  'csv.refunds': 'Refunds',
  'csv.disputes': 'Disputes',
  'csv.tips': 'Tips by person',
  'csv.tipRecords': 'Tip records',
  'csv.vat': 'VAT by rate',
  'csv.cashUps': 'Cash-ups',
  'csv.sales': 'Sales',
  'csv.sales.byPeriod': 'Sales by period',
  'csv.sales.byType': 'Services and products',
  'csv.sales.byService': 'Sales by service',
  'csv.sales.byCategory': 'Sales by category',
  'csv.sales.byPerformer': 'Services by team member',
  'csv.sales.bySeller': 'Products by team member',
  'csv.sales.discounts': 'Discounts',
  'csv.sales.margin': 'Margin and cost of products',
  'csv.sales.byProduct': 'Sales by product',
  'csv.sales.byBrand': 'Sales by brand',
  'csv.sales.productCategories': 'Products by category',
  'csv.sales.stock': 'Stock',

  // ─── Cash-ups (CashUpsSection.tsx) ────────────────────────────────────────
  'cu.title': 'Cash-ups',
  'cu.till': 'Till',
  'cu.closedBy': 'Closed by',
  'cu.expected': 'Expected',
  'cu.counted': 'Counted',
  'cu.difference': 'Difference',
  'cu.totals': 'Over {over}, short {short}, net {net}.',
  'cu.outside.title': 'Cash outside a till session: {amount}',
  'cu.outside.help': "Taken in an older version of the ResNeo app while no till was open. It isn't in any till's expected cash.",
  'cu.outside.takenBy': 'Taken by',

  // ─── Payouts (PayoutsSection.tsx, beside `rep.payout.*` in lib/pos/copy.ts) ─
  'po.coveredAmount': 'What the {amount} payout arriving {date} covered',
  'po.covered': 'Covered',
  'po.for': 'For',
  'po.cardEnding': '{label}, card ending {last4}',

  // ─── Sales (SalesSection.tsx, SalesProductSections.tsx) ───────────────────
  'sl.help': 'What you sold, on the day each sale was paid. Deposits paid earlier count as part of the sale, not as new money.',
  'sl.title': 'Sales, {range}',
  'sl.refundsSub': 'Refunds {amount}',
  'sl.count': 'Number of sales',
  'sl.average': 'Average sale',
  'sl.retailPerVisit': 'Retail per visit',
  'sl.visits': '{count} visits with a service',
  'sl.visit': '1 visit with a service',
  'sl.discountsGiven': 'Discounts given',
  'sl.applied': 'Deposits and earlier payments applied',
  'sl.vatIncluded': 'VAT included',
  'sl.value': 'Value',
  'sl.servicesAndProducts': 'Services and products',
  'sl.type': 'Type',
  'sl.kind': 'Kind',
  'sl.byService': 'By service',
  'sl.service': 'Service',
  'sl.byCategory': 'By category',
  'sl.byPerformer': 'Services by team member',
  'sl.bySeller': 'Products by team member',
  'sl.shareNote': 'Where a line was shared, each person gets their share.',
  'sl.services': 'Services',
  'sl.products': 'Products',
  'sl.other': 'Other',
  'sl.discountsTitle': 'Discounts by reason and person',
  'sl.discountsByReason': 'By reason',
  'sl.discountsByPerson': 'By person',
  'sl.margin': 'Margin and cost of products',
  'sl.margin.help': 'Uses what each product cost you when it was sold, from your delivery costs.',
  'sl.margin.revenue': 'Product sales before VAT',
  'sl.margin.cog': 'Cost of goods',
  'sl.margin.margin': 'Margin',
  'sl.margin.pct': 'Margin %',
  'sl.margin.noCost.one': "1 product sold had no cost price, so it's left out of the margin. Add cost prices in Products.",
  'sl.margin.noCost.many': "{count} products sold had no cost price, so they're left out of the margin. Add cost prices in Products.",
  'sl.margin.restocked.one': '1 item came back and went back in stock, so its cost is taken off.',
  'sl.margin.restocked.many': '{count} items came back and went back in stock, so their cost is taken off.',
  'sl.byProduct': 'By product',
  'sl.brand': 'Brand',
  'sl.noBrand': 'No brand',
  'sl.byBrand': 'By brand',
  'sl.productCategories': 'Products by category',
  'sl.stock': 'Stock value, slow sellers and sell-through',
  'sl.stock.cost': 'Stock value at cost',
  'sl.stock.retail': 'Stock value at retail',
  'sl.stock.units': 'Items in stock',
  'sl.stock.dead': 'Not sold in 90 days',
  'sl.stock.inStock': 'In stock',
  'sl.stock.valueCost': 'Value at cost',
  'sl.stock.sellThrough': 'Sell-through this period',
  'sl.stock.sold': 'Sold',
  'sl.stock.received': 'Received',
  'sl.stock.sellThroughCol': 'Sell-through',
  'sl.stock.nothingReceived': 'Nothing received',
  'sl.stock.note': 'The full stock reports are on the Stock page.',
  'sl.marginUnknown': 'Not known',

  // ─── Commission (src/lib/pos/commission/copy.ts) ──────────────────────────
  'rep.c.help': 'Commission on sales completed in this period, shared by who gets the credit for each line.',
  'rep.c.onlyTill': 'Only sales checked out in Checkout count, so check out every visit to make sure nobody misses out.',
  'rep.c.table': 'Commission by person',
  'rep.c.col.person': 'Team member',
  'rep.c.col.servicesBase': 'Services sold',
  'rep.c.col.servicesComm': 'Services commission',
  'rep.c.col.productsBase': 'Products sold',
  'rep.c.col.productsComm': 'Products commission',
  'rep.c.col.vouchersBase': 'Vouchers sold',
  'rep.c.col.vouchersComm': 'Vouchers commission',
  'rep.c.col.total': 'Total commission',
  'rep.c.col.tips': 'Tips (for reference)',
  'rep.c.tipsNote': "Tips aren't commission. They're here so you can see everything in one place.",
  'rep.c.lines': "{staffName}'s sales",
  'rep.c.line.sale': 'Sale {saleNo}',
  'rep.c.refundRow': 'Refund on Sale {saleNo}',
  'rep.c.changed': 'Changed since you exported it on {date}',
  'rep.c.changed.line': 'Credit changed after the export',
  'rep.c.noRates': "You haven't set any commission rates yet.",
  'rep.c.everyone': 'Everyone',
  'rep.c.exportLines': 'Export CSV: {lines}',
  'rep.c.item': 'Item',
  'rep.c.share': 'Share',
  'rep.c.base': 'Base',
  'rep.c.rate': 'Rate',
  'rep.c.commission': 'Commission',
  'rep.c.sale': 'Sale',

  // ─── Vouchers (voucher-copy.ts, VouchersSection.tsx, AllVouchersCard.tsx) ─
  'rep.v.help':
    "Vouchers sold, used, expired and refunded in this period, and what's still to be spent. Money for a voucher counts in Takings on the day it's paid. What it pays for counts in Sales when it's used.",
  'rep.v.sold': 'Sold',
  'rep.v.redeemed': 'Used',
  'rep.v.expired': 'Expired unused',
  'rep.v.expired.help': 'The value left on vouchers when they ran out. Ask your accountant how to treat it.',
  'rep.v.refunded': 'Refunded',
  'rep.v.outstanding': 'Still to be spent',
  'rep.v.asAt': 'On {date}',
  'rep.v.existing': 'Added from before ResNeo',
  'rep.v.credit': 'Account credit',
  'rep.v.list': 'All vouchers',
  'rep.v.given': 'Given',
  'rep.v.title': 'Vouchers, {from} to {to}',
  'rep.v.count.one': '1 voucher',
  'rep.v.count.many': '{count} vouchers',
  'rep.v.search': 'Search by the last four characters or a name',
  'rep.v.searchLabel': 'Search vouchers',
  'rep.v.all': 'All',
  'rep.v.loading': 'Loading vouchers...',
  'rep.v.showing': 'Showing {shown} of {total}',
  'rep.v.more': 'Show more',
  'rep.v.ending': 'Voucher ending {last4}',
  'rep.v.for': 'For {name}',
  'rep.v.boughtBy': 'Bought by {name}',
  'rep.v.issued': 'Issued {date}',
  'rep.v.balanceOf': '{balance} of {initial}',

  // ─── One voucher (VoucherSheet.tsx, voucher-ui.tsx) ───────────────────────
  'vch.title': 'Gift voucher ending {last4}',
  'vch.initial': 'Started at {amount}',
  'vch.issued': 'Bought on {date}',
  'vch.sent': 'Emailed to {email} on {date}',
  'vch.scheduled': 'Will be emailed to {email} on {date}',
  'vch.notSent': 'Not emailed',
  'vch.disputed': "The payment for this voucher is disputed, so it's on hold until the dispute closes.",
  'vch.onHold': "This voucher is on hold, so it can't be used until an admin takes it off hold.",
  'vch.onHoldWhy': "This voucher is on hold ({reason}), so it can't be used until an admin takes it off hold.",
  'vch.mov.issue': 'Bought',
  'vch.mov.redeem': 'Used on Sale {saleNo}',
  'vch.mov.redeem_reversal': 'Refunded from Sale {saleNo}',
  'vch.mov.refund_in': 'Refund added as credit, from Sale {saleNo}',
  'vch.mov.expire': 'Ran out',
  'vch.mov.extend': 'Extended to {date}',
  'vch.mov.adjust': 'Changed by {staffName}: {reason}',
  'vch.mov.cancel': 'Cancelled: {reason}',
  'vch.pdf': 'Download the voucher',
  'vch.resend': 'Send the email again',
  'vch.resend.to': 'Their email, to send it to them',
  'vch.resend.holder': "Holder's email (optional)",
  'vch.extend': 'Extend',
  'vch.extend.title': 'Extend this voucher',
  'vch.extend.done': 'It can now be used until {date}.',
  'vch.freeze': 'Put on hold',
  'vch.unfreeze': 'Take off hold',
  'vch.cancel': 'Cancel voucher',
  'vch.cancel.title': 'Cancel this gift voucher?',
  'vch.cancel.body': "It can't be used after this. This doesn't refund anyone: to give money back, refund the sale it was bought on.",
  'vch.history': 'See history',
  'vch.adjust': 'Change the amount left',
  'vch.adjust.add': 'Add to it',
  'vch.adjust.remove': 'Take off it',
  'vch.adjust.save': 'Save change',
  'vch.reason': 'Reason',
  'vch.amount': 'Amount',
  'vch.useBy': 'Use by',
  'vch.noExpiry': 'No expiry date',
  'vch.pdfFailed': "We couldn't get the voucher. Please try again.",
  'vch.loadError': "We couldn't find that gift voucher.",

  // ─── Adding an existing voucher (StoredValueDialogs.tsx) ──────────────────
  'vadd.open': 'Add an existing voucher',
  'vadd.title': 'Add an existing voucher',
  'vadd.body':
    "Record a voucher you sold before ResNeo, on paper or with Booksy or Fresha, so you can take it here. It isn't money taken today, so it won't show in your takings.",
  'vadd.codeChoice': 'Voucher code',
  'vadd.code.own': 'Use the code printed on the voucher',
  'vadd.code.new': 'Give it a new ResNeo code',
  'vadd.code.taken': 'Another voucher already uses that code.',
  'vadd.code.invalid': "That doesn't look like a voucher code. Check it and try again.",
  'vadd.balance': 'Amount left on it',
  'vadd.expiry': 'Use by',
  'vadd.noExpiry': 'No expiry date',
  'vadd.holder': "Holder's name (optional)",
  'vadd.email': "Holder's email (optional)",
  'vadd.client': 'Link to a {client} (optional)',
  'vadd.clientRemove': 'Remove {name}',
  'vadd.note': 'Note (optional)',
  'vadd.confirm': 'Add voucher',
  'vadd.done': 'Gift voucher ending {last4} added, with {amount} on it.',
  'vadd.newCode': "The new code is {code}. Write it on the voucher or print a new one now. You won't see the full code here again.",
  'vadd.finish': 'Done',

  // ─── Importing vouchers (VoucherImportDialog.tsx) ─────────────────────────
  'vimp.open': 'Import vouchers from a file',
  'vimp.title': 'Import gift vouchers',
  'vimp.body': "Bring in vouchers you sold before ResNeo, from a spreadsheet saved as CSV. They won't show in your takings.",
  'vimp.template': 'Download a template',
  'vimp.file': 'CSV file',
  'vimp.choose': 'Choose a CSV file',
  'vimp.tooBig': 'The file is larger than 5 MB.',
  'vimp.unreadable': "We couldn't read that file. Save it as CSV and try again.",
  'vimp.optional': '{label} (optional)',
  'vimp.chooseColumn': 'Choose a column',
  'vimp.notInFile': 'Not in the file',
  'vimp.check': 'Check the file',
  'vimp.back': 'Back',
  'vimp.row': 'Row {row}',
  'vimp.row.new': 'Will be added',
  'vimp.row.exists': "Code already used, so it's skipped",
  'vimp.row.error': 'Problem: {problem}',
  'vimp.summary': '{count} vouchers to add, worth {amount} in total. {problems} rows have problems.',
  'vimp.newCodes': 'Give every voucher a new ResNeo code',
  'vimp.commit': 'Import vouchers',
  'vimp.done': '{count} vouchers added, worth {amount} in total.',
  'vimp.downloadCodes': 'Download the new codes. You can only do this once.',
  'vimp.col.code': 'Code',
  'vimp.col.balance': 'Amount left',
  'vimp.col.expiry': 'Use by',
  'vimp.col.holder_name': "Holder's name",
  'vimp.col.holder_email': "Holder's email",
  'vimp.col.note': 'Note',

  // ─── Overview renames where Takings shows (ReportsView.tsx) ───────────────
  'ov.depositsByBookingDate': 'Deposits by booking date',

  // ─── Export your data: the POS kinds (DataExportSection.tsx) ──────────────
  'exp.sales': 'Sales',
  'exp.sales.hint': 'Every line of every completed sale: the sale number, {client}, item, quantity, price, discounts, VAT, who did the service and who sold it.',
  'exp.sales.range': 'Sales are chosen by the day each sale was paid.',
  'exp.payments': 'Payments',
  'exp.payments.hint': 'Every payment and refund, from checkout, online deposits, fees, class passes and memberships, with the method, card type, tip and who took it.',
  'exp.payments.range': 'Payments are chosen by the day the money moved.',
  'exp.products': 'Products',
  'exp.products.hint': 'Every product option with its brand, category, SKU, barcodes, price, cost and, where you count it, stock.',
  'exp.products.range': 'Products are not chosen by date: every product is included.',
  'exp.stock': 'Stock movements',
  'exp.stock.hint': 'Every change to your stock: sales, deliveries, adjustments and stocktakes, with the value at cost and who made it.',
  'exp.stock.range': 'Stock movements are chosen by the day they happened.',
} as const;

export type ReportsCopyId = keyof typeof REPORTS_COPY;

/** One of the words above, with its placeholders filled. */
export function reportsCopy(id: ReportsCopyId, vars: CopyVars = {}): string {
  return fillCopy(REPORTS_COPY[id], vars);
}
