import type { PosPayment, PosSale, PosSaleLine } from '@/types/pos';

/**
 * Sale fixtures for the Checkout tests, shaped as `GET /api/venue/pos/sales/[id]` returns them.
 * Test-only: nothing in the app imports this file.
 */

export function makeLine(over: Partial<PosSaleLine> = {}): PosSaleLine {
  return {
    id: 'line-1',
    line_no: 1,
    line_type: 'service',
    parent_line_id: null,
    booking_id: null,
    service_item_id: null,
    service_variant_id: null,
    product_id: null,
    variant_id: null,
    name: 'Cut and finish',
    option_name: null,
    reporting_group: 'services',
    quantity: 1,
    list_unit_price_pence: 4000,
    unit_price_pence: 4000,
    price_change_reason: null,
    paid_by_credit: false,
    line_discount_pence: 0,
    sale_discount_share_pence: 0,
    total_pence: 4000,
    tax_rate_bps: 0,
    tax_code: 'O',
    tax_pence: 0,
    tip_eligible: true,
    walkin_booking: false,
    refunded_quantity: 0,
    refunded_pence: 0,
    performer: null,
    seller: null,
    attributions: [],
    booking: null,
    ...over,
  };
}

export function makePayment(over: Partial<PosPayment> = {}): PosPayment {
  return {
    id: 'pay-1',
    method: 'cash',
    is_money: true,
    status: 'succeeded',
    amount_pence: 1000,
    tip_pence: 0,
    refunded_pence: 0,
    refunded_tip_pence: 0,
    refundable_pence: 1000,
    refundable_tip_pence: 0,
    cash_tendered_pence: null,
    change_given_pence: null,
    payment_type_id: null,
    payment_type_name: null,
    reference: null,
    applied_booking_id: null,
    card_brand: null,
    card_last4: null,
    reader_label: null,
    operator_name: null,
    failure_code: null,
    failure_message: null,
    stripe_payment_intent_id: null,
    business_date: '2026-10-09',
    created_at: '2026-10-09T10:00:00Z',
    succeeded_at: '2026-10-09T10:00:00Z',
    ...over,
  };
}

export function makeSale(over: Partial<PosSale> = {}): PosSale {
  return {
    id: 'sale-1',
    number: 12,
    number_label: 'R-12',
    channel: 'app',
    status: 'open',
    version: 3,
    currency: 'GBP',
    guest: null,
    subtotal_pence: 4000,
    discount_pence: 0,
    tax_pence: 0,
    total_pence: 4000,
    paid_pence: 0,
    applied_pence: 0,
    tip_pence: 0,
    refunded_pence: 0,
    returned_pence: 0,
    pending_pence: 0,
    reserved_pence: 0,
    balance_due_pence: 4000,
    refund_status: 'none',
    opened_business_date: '2026-10-09',
    business_date: null,
    created_at: '2026-10-09T10:00:00Z',
    completed_at: null,
    voided_at: null,
    void_reason: null,
    cancel_requested_at: null,
    till_id: null,
    notes: null,
    created_by_name: 'Sam',
    operator: { staff_id: 'staff-1', calendar_id: null, name: 'Sam' },
    parked: null,
    payment_lock_payment_id: null,
    lines: [makeLine()],
    discounts: [],
    payments: [],
    refunds: [],
    returns: [],
    tips: [],
    ...over,
  };
}
