/**
 * The Collective area's words, copied from the web's `collectiveCopy` table
 * (`src/lib/linked-accounts/collective-copy.ts`, 2026-09-17) so the two read the same.
 * Regenerate rather than edit by hand when the web wording changes.
 */

export const AREA_COPY = {
  "bm.members.alsoRuns": "Also runs {modelList}, which stay on its own booking page.",
  "bp.members.cancelInvite": "Cancel invitation",
  "bp.members.history": "History",
  "common.pill.collective": "Collective",
  "common.pill.couldNotUpdate": "Could not update",
  "common.pill.fromHost": "From {host}",
  "common.pill.hidden": "Hidden",
  "common.pill.parked": "Parked",
  "common.pill.paused": "Paused",
  "common.pill.retired": "Retired",
  "common.pill.settingUp": "Setting up",
  "common.pill.turnedOffByHost": "Turned off by {host}",
  "common.pill.upToDate": "Up to date",
  "common.pill.updating": "Updating",
  "dissolve.button": "End {collective}",
  "dissolve.hint": "The shared page stops taking bookings. Every venue keeps its services, calendars, clients and bookings.",
  "dissolve.message": "The {collective} page stops taking bookings straight away. Every venue keeps its services, calendars, clients and bookings, and its own booking page comes back. For 90 days, old links to the {collective} page show a page listing each venue's own booking page.",
  "dissolve.sectionTitle": "End the collective",
  "dissolve.title": "End {collective}?",
  "dissolve.typeToConfirm": "Type {collective} to confirm",
  "history.empty": "Nothing has changed yet.",
  "history.export": "Download this history",
  "history.filter.all": "All changes",
  "history.filter.anyVenue": "Every venue",
  "history.filter.calendars": "Calendars",
  "history.filter.from": "From",
  "history.filter.members": "Members",
  "history.filter.services": "Services",
  "history.filter.to": "To",
  "history.filter.venue": "Venue",
  "history.more": "Load more",
  "history.title": "{collective} history",
  "notify.hostRequest.body": "If you accept, you manage the services on the {collective} page for every venue, including their prices and forms.",
  "ov.bulk.addCalendars": "Choose calendars",
  "ov.bulk.confirm.confirm": "Save changes",
  "ov.bulk.confirm.message": "This changes {count} services at {venueList}.",
  "ov.bulk.confirm.messageOne": "This changes {count} service at {venueList}.",
  "ov.bulk.confirm.title": "Save these changes?",
  "ov.bulk.discard": "Discard",
  "ov.bulk.offer": "Put on the page",
  "ov.bulk.removeCalendars": "Remove calendars",
  "ov.bulk.retry": "Try these again",
  "ov.bulk.save": "Save {count} changes",
  "ov.bulk.saveOne": "Save {count} change",
  "ov.bulk.selected": "{services} at {venues} selected",
  "ov.bulk.someFailed": "{count} changes did not go through. They are still here, so you can try again.",
  "ov.bulk.someFailedOne": "1 change did not go through. It is still here, so you can try again.",
  "ov.bulk.venue": "venue",
  "ov.bulk.venues": "venues",
  "ov.bulk.withdraw": "Take off the page",
  "ov.filter.all": "All services",
  "ov.filter.attention": "Needs attention",
  "ov.filter.offPage": "Not on the page",
  "ov.grid.cell.all": "All calendars",
  "ov.grid.cell.hidden": "Hidden from guests",
  "ov.grid.cell.none": "No calendars",
  "ov.grid.cell.offPage": "Not on the page",
  "ov.grid.cell.some": "Some calendars",
  "ov.grid.cell.staged": "{count} staged",
  "ov.grid.done": "Done",
  "ov.grid.empty": "No services match.",
  "ov.grid.search": "Search services",
  "ov.preview.button": "See what each venue will show",
  "ov.preview.failed": "Could not work out the preview. Your changes are still here.",
  "ov.preview.loading": "Working out what each venue will show...",
  "ov.preview.nothing": "Guests will not be able to book anything with {venue} on the page.",
  "ov.preview.shows": "Guests can book: {services}.",
  "ov.preview.title": "What guests will see",
  "ov.preview.willHide": "This will not be bookable at {venue}, because {reason}.",
  "ov.subtitle": "Who is in it, what is on the page, and which calendars offer what.",
  "ov.tab.history": "History",
  "ov.tab.overview": "Services",
  "ov.tab.venues": "Venues",
  "ov.todo.failed": "{count} services could not be updated at {venue}.",
  "ov.todo.failedOne": "{count} service could not be updated at {venue}.",
  "ov.todo.formsOff": "{venue} has forms switched off, so {count} services that need a form are hidden from guests there.",
  "ov.todo.formsOffOne": "{venue} has forms switched off, so {count} service that needs a form is hidden from guests there.",
  "ov.todo.formsOffYou": "Your forms are switched off, so {count} services that need a form are hidden from your guests.",
  "ov.todo.formsOffYouOne": "Your forms are switched off, so {count} service that needs a form is hidden from your guests.",
  "ov.todo.heading": "What needs you",
  "ov.todo.newVenue": "{venue} has joined. Choose their calendars on {count} services.",
  "ov.todo.newVenueOne": "{venue} has joined. Choose their calendars on {count} service.",
  "ov.todo.noCalendars": "{service} is on the page but no calendar offers it, so guests cannot book it.",
  "ov.todo.noStripe": "{venue} cannot take card payments yet, so {count} paid services are hidden from guests there.",
  "ov.todo.noStripeOne": "{venue} cannot take card payments yet, so {count} paid service is hidden from guests there.",
  "ov.todo.noStripeYou": "You cannot take card payments yet, so {count} paid services are hidden from your guests.",
  "ov.todo.noStripeYouOne": "You cannot take card payments yet, so {count} paid service is hidden from your guests.",
  "ov.venue.calendar": "calendar",
  "ov.venue.calendars": "calendars",
  "ov.venue.counts": "{services} services, {calendars} calendars on the page",
  "ov.venue.countsWords": "{services}, {calendars} on the page",
  "ov.venue.failed": "An update did not go through.",
  "ov.venue.service": "service",
  "ov.venue.services": "services",
  "ov.venue.upToDate": "Up to date with the page.",
  "ov.venue.updating": "Updating. Its calendars take new bookings again in a moment.",
  "ov.venues.cancelMessage": "{venue} will no longer be able to join. You can invite it again later.",
  "ov.venues.cancelTitle": "Cancel the invitation to {venue}?",
  "ov.venues.host": "Host",
  "ov.venues.invite": "Invite a venue",
  "ov.venues.invited": "(invited)",
  "ov.venues.member": "Member",
  "ov.venues.remove": "Remove",
  "ov.venues.removeMessage": "{venue} stops being part of {collective}. Its copies of your services become its own, and bookings already made are not changed.",
  "ov.venues.removeTitle": "Remove {venue} from {collective}?",
  "svc.cal.chip.buffer": "Custom buffer {minutes} min",
  "svc.cal.chip.colour": "Custom colour",
  "svc.cal.chip.deposit": "Custom deposit {price}",
  "svc.cal.chip.length": "Custom length {minutes} min",
  "svc.cal.chip.name": "Custom name",
  "svc.cal.chip.price": "Custom price {price}",
  "svc.cal.heading": "Calendars that offer this service",
  "svc.cal.noCalendars": "{venue} has no active calendars yet.",
  "svc.cal.venueYou": "{venue} (you)",
  "svc.cal.warn.failed": "Could not update at {venue}: {reason}.",
  "svc.cal.warn.formsOff": "{venue} has forms switched off, so its calendars are hidden for this service until it turns them on.",
  "svc.cal.warn.noStripe": "{venue} cannot take card payments yet, so guests cannot book its calendars for this service online. Its team can still book it.",
  "svc.cal.warn.awaiting": "{venue} has a service with the same name and has been asked whether to use it. Its calendars can offer this once it answers.",
  "svc.card.parked": "Parked while {collective} is live. Put it on the page to take bookings for it.",
  "ov.todo.awaiting": "{venue} has been asked whether to use its own {service} for the one on the page. Its calendars can be chosen once it answers.",
  "svc.cal.warn.settingUp": "Setting up at {venue}. Its calendars can take bookings once this finishes.",
  "svc.cal.warn.suspended": "{venue}'s subscription has lapsed, so its calendars are hidden from the {collective} page until it is put right.",
  "svc.card.hiddenAt": "Hidden at {venue}",
  "svc.member.card.connectStripe": "Connect Stripe",
  "svc.member.card.turnOn": "Turn on",
  "svc.member.section.fromHostCaption": "Managed by {host} for {collective}",
  "svc.member.section.fromHostTitle": "From {host}",
  "svc.member.section.parkedCaption": "Yours to edit, but nobody can book these while you are part of {collective}. Bookings already made are not changed. To offer one now, suggest it to {host}.",
  "svc.member.section.parkedTitle": "Parked while you are part of {collective}",
  "svc.member.section.retired": "No longer offered by {host}",
  "svc.member.section.retiredCaption": "{host} took these off the {collective} page. They cannot be booked. Bookings already made are not changed.",
  "svc.offer.chooseCalendars": "Choose calendars",
  "svc.save.retry": "Retry now",
  "sync.reason.unknown": "something went wrong on our side",
  "transfer.accept.1": "You will control the services on the page for every venue: names, prices, deposits, payment rules, options, add-ons and forms.",
  "transfer.accept.2": "{host}'s services on the page become services you manage, in {host}'s account.",
  "transfer.accept.3": "The {collective} page will show your address, phone and opening hours.",
  "transfer.accept.4": "Clients keep paying the venue whose calendar they book.",
  "transfer.accept.confirm": "Accept and host",
  "transfer.accept.consent": "I agree to host {collective} and manage its services for every venue.",
  "transfer.accept.title": "Take over hosting {collective}?",
  "transfer.ask.button": "Ask to host",
  "transfer.ask.confirm": "Send request",
  "transfer.ask.message": "If {venue} accepts, it controls the services on the {collective} page for every venue, including yours. The page then shows {venue}'s address, phone and opening hours. Every venue is told, and hosting moves 14 days after {venue} accepts.",
  "transfer.ask.title": "Ask {venue} to host {collective}?",
  "transfer.cancel": "Cancel the move",
  "transfer.cancel.message": "{venue} is told, and {collective} keeps its current host.",
  "transfer.cancel.title": "Cancel the move of hosting to {venue}?",
  "transfer.decline": "Say no",
  "transfer.error.consent": "Please read what hosting involves and tick the box to agree before accepting.",
  "transfer.paused.body": "{collective} has no host, so its page is not taking bookings. One venue can take over hosting, or {collective} ends after 30 days and every venue keeps everything.",
  "transfer.paused.takeOver": "Take over hosting",
  "transfer.paused.title": "{collective} is paused",
  "transfer.pending.asked": "Asked {venue} to host. Waiting for {venue} to answer.",
  "transfer.pending.scheduled": "{venue} will host {collective} from {date}.",
  "transfer.request.title": "{host} asked you to host {collective}",
  "transfer.review": "Review request",
} as const;

export type AreaCopyId = keyof typeof AREA_COPY;

/** Fill {placeholders}; a missing value leaves the placeholder, as on the web. */
export function areaCopy(id: AreaCopyId, params: Record<string, string | number | null | undefined> = {}): string {
  return AREA_COPY[id].replace(/\{(\w+)\}/g, (whole, name: string) => {
    const value = params[name];
    return value == null ? whole : String(value);
  });
}

/** Why a service would not be bookable at a venue (web `PREVIEW_REASON_WORDS`). */
export const PREVIEW_REASON_WORDS: Record<string, string> = {
  "no_calendars": "no calendar there offers it",
  "payments": "card payments are not set up there",
  "forms": "forms are switched off there",
  "suspended": "that venue's subscription has lapsed",
  "staff_only": "it is staff bookings only",
  "behind": "that venue is still updating"
};

/** Web `HOST_TRANSFER_CONSENT_VERSION`: sent with accepting or taking over hosting. */
export const HOST_TRANSFER_CONSENT_VERSION = "host-transfer-2026-09";

/** "Light 3", "A and B", "A, B and C", or "A, B and 3 more" (web `formatVenueList`). */
export function formatVenueList(names: string[], namesShownWhenLong = 2): string {
  const clean = names.map((n) => n.trim()).filter(Boolean);
  if (clean.length === 0) return '';
  if (clean.length === 1) return clean[0]!;
  if (clean.length <= 3) return `${clean.slice(0, -1).join(', ')} and ${clean[clean.length - 1]}`;
  const shown = clean.slice(0, namesShownWhenLong);
  return `${shown.join(', ')} and ${clean.length - shown.length} more`;
}
