/**
 * Copy for the link + collective setup flows (web `src/lib/linked-accounts/collective-copy.ts`,
 * the `setup.*`, `respond.*`, `finish.*`, `banner.*`, `join.*`, `create.*` and `la.row.*` keys;
 * Docs/link-and-collective-setup-wizard-plan.md). Same keys and sentences as the web, so the two
 * never disagree.
 */
export const SETUP_COPY = {
  'svc.card.parked': 'Parked while {collective} is live. Put it on the page to take bookings for it.',
  'ov.todo.awaiting': '{venue} has been asked whether to use its own {service} for the one on the page. Its calendars can be chosen once it answers.',
  'bm.currency.blocked': '{venue} takes payment in {currency} and the collective uses {hostCurrency}. Every venue in a collective has to use the same currency.',
  'svc.member.adopt.title': '{host} wants to use your {service}',
  'svc.member.adopt.message': '{host} has put {service} on the {collective} page. You can use your own {service} for it, so its calendars and bookings stay as they are, or keep yours separate. If you keep yours separate, it is parked while you are part of {collective}.',
  'svc.member.adopt.useMine': 'Use my {service}',
  'svc.member.adopt.keepSeparate': 'Keep mine separate',
  'svc.member.adopt.open': 'Choose',
  'create.what.title': 'What a collective is',
  'create.what.1': 'Two or more venues sell their appointments on one booking page, as one business.',
  'create.what.2': 'The host puts services on that page and sets their prices, deposits and forms for every venue.',
  'create.what.3': 'Each venue keeps its own calendars, clients, bookings and payments.',
  'create.what.host': '{venue} will be the host.',
  'create.name.label': 'Collective name',
  'create.name.help': 'Guests see this name on the booking page and in their emails.',
  'create.address.preview': '{origin}/book/c/{slug}',
  'create.address.checking': 'Checking this address...',
  'create.address.free': 'This address is free.',
  'create.address.taken': 'That address is taken. Try another.',
  'create.address.format': 'Use lower-case letters, numbers and hyphens only.',
  'create.disabled.address': 'Choose a free address to continue.',
  'create.venues.warn.noStripe': '{venue} has not connected Stripe. It can join, but guests cannot book its calendars online for services that take a payment.',
  'create.venues.blocked.otherCollective': 'Already part of another collective',
  'create.venues.blocked.timezone': 'In {timezone}, not {yourTimezone}',
  'create.venues.blocked.currency': 'Uses {currency}, not {yourCurrency}',
  'create.venues.blocked.plan': 'Their plan does not include collectives',
  'create.venues.blocked.bookingModel': 'Takes bookings in a different way from you',
  'create.venues.blocked.permissions': 'Your link with {venue} does not share full calendar details yet.',
  'create.changes.title': 'What changes when {collective} starts',
  'create.changes.intro': 'Here is what happens for you and for each venue you invite, once two venues are in.',
  'create.changes.address.note': 'Guests who visit any of these addresses land on the {collective} page.',
  'create.changes.address.when': 'This starts once two venues are in and at least one calendar offers a service. Until then, every page stays as it is.',
  'create.changes.services.title': 'The services come from you',
  'create.changes.services.body': 'Services you put on the page are set up in each venue\'s account, with your prices, deposits and forms. You change them for every venue at once.',
  'create.changes.owns.title': 'Each venue keeps what is its own',
  'create.changes.owns.body': 'Its calendars, working hours, clients, bookings and payments stay with that venue. Clients pay the venue they book with.',
  'create.changes.clients.title': 'Your account links stay as they are',
  'create.changes.clients.body': 'Every venue in {collective} is already linked with the others, which is how you see each other\'s clients and bookings. {collective} does not change those links, and leaving or ending it does not end them. Its reports show every venue\'s takings, each named.',
  'create.changes.ending': 'Any venue can leave at any time, and you can end {collective} at any time. Every venue keeps its services, calendars, clients and bookings.',
  'create.changes.ack': 'I understand what changes for {venue} and for the venues I invite.',
  'create.changes.help': 'Read more about collectives',
  'bm.invite.noAppointments': '{venue} does not offer appointments, so it cannot join a collective yet. A collective page shows appointments only.',
  'bm.join.otherModels': 'You also run {modelList}. Those stay on your own booking page and are not shown on the {collective} page.',
  'join.title': 'Join {collective}',
  'join.step': 'Step {n} of {total}',
  'join.step.means': 'What joining means',
  'join.step.services': 'Your services',
  'join.step.forms': 'Forms you already use',
  'join.step.check': 'Check and join',
  'join.means.1': '{host} sets up the services on the {collective} page in your account and controls them: names, descriptions, prices, deposits, payment rules, options, add-ons and forms.',
  'join.means.2': 'Clients pay you, through your own Stripe account, at the prices {host} sets.',
  'join.means.3': 'You choose which of your calendars offer each service. Your working hours and closures stay yours.',
  'join.means.4': 'Your clients and bookings stay yours.',
  'join.means.5': 'While you are part of {collective}, guests who visit your own booking page land on the {collective} page.',
  'join.means.6': 'Your services that are not on the {collective} page are parked while you are part of {collective}: nobody can book them, your team included. They stay yours to edit, bookings already made for them are not changed, and you can ask {host} to add any of them.',
  'join.means.7': 'You can leave at any time. You keep every service and booking.',
  'join.warn.noStripe': 'You have not connected Stripe. {count} services on the page take a deposit, full payment or card hold, so guests cannot book those with you online until you connect it.',
  'join.warn.formsOn': 'Some services ask for forms. Your calendars can offer those only while compliance records are switched on for your venue, and once on they stay on while you are part of {collective}. We do not switch them on for you.',
  'join.block.timezone': 'You cannot join because your venue is in {yourTimezone} and {collective} is in {timezone}. Change your timezone under Profile first.',
  'join.block.currency': 'You cannot join because your venue uses {yourCurrency} and {collective} uses {currency}.',
  'join.block.otherCollective': 'Your venue is already part of {otherCollective}. Leave it before joining another.',
  'join.block.otherCollectiveGeneric': 'Your venue is already part of another collective. Leave it before joining this one.',
  'join.block.bookingModel': 'You cannot join because your venue takes bookings in a different way from {collective}.',
  'join.block.links': 'You cannot join yet because your account links with every venue in {collective} need full access both ways. Check them under Linked accounts.',
  'join.block.unknown': 'You cannot join right now. Please try again, or contact support if this keeps happening.',
  'join.services.sameName.heading': 'Services with the same name',
  'join.services.sameName.help': 'You already have services with these names. Choose whether to use yours or add {host}\'s as new.',
  'join.services.addNew': 'Add {host}\'s as a new service',
  'join.services.useMine': 'Use my {service}',
  'join.services.useMine.note': 'Your {service} keeps its calendars and bookings. Its settings change to {host}\'s. Bookings already made keep their price.',
  'join.map.heading': 'Match your options',
  'join.map.yours': 'Your option',
  'join.map.theirs': '{host}\'s option',
  'join.map.keepOld': 'Keep for existing bookings only',
  'join.services.own.heading': 'Your other services',
  'join.services.own.help': 'These are not on the {collective} page, so they are parked while you are part of {collective}. Bookings already made for them are not changed. If one should be on the page, ask {host} to add it.',
  'join.services.park': 'Park it until I leave',
  'join.services.ask': 'Ask {host} to add it to {collective}',
  'join.services.none': 'You have no services of your own to decide about.',
  'join.forms.useExisting': 'Use my existing {form}, so records my clients already gave still count',
  'join.forms.useTheirs': 'Use {host}\'s version as a separate form',
  'join.forms.note': 'Either way, {host} decides which forms its services ask for.',
  'join.forms.none': 'None of your forms share a name with the ones {collective} uses.',
  'join.summary.setup': '{count} services from {host} will be set up in your account.',
  'join.summary.useMine': '{count} of your services will be used for services from {host}.',
  'join.summary.park': '{count} of your services will be parked until you leave {collective}.',
  'join.summary.ask': '{host} will be asked to add {count} of your services.',
  'join.consent': 'I understand that guests who visit {venue}\'s booking page will be sent to the {collective} page, that {host} manages the services on it for {venue}, and that the venues in {collective} can see each other\'s clients, bookings and takings through our account links.',
  'join.confirm': 'Join {collective}',
  'join.next': 'Next',
  'join.back': 'Back',
  'join.error.consent': 'Please open ResNeo on the web to read what joining means, then accept there.',
  'join.loading': 'Getting your services ready to compare...',
  'banner.request': '{venue} wants to link with your venue.',
  'banner.requestWithCollective': '{venue} wants to link with your venue and start {collective}, a shared booking page.',
  'banner.change': '{venue} proposed a permission change to your link.',
  'banner.setup': '{venueList} joined {collective}. Two short steps make your shared booking page live.',
  'banner.review.cta': 'Review request',
  'banner.change.cta': 'Review change',
  'banner.setup.cta': 'Continue setup',
  'banner.dismiss': 'Dismiss for 24h',
  'banner.waiting': 'Waiting for {venue} to review your link request. The link starts as soon as they accept.',
  'banner.waitingWithCollective': 'Waiting for {venue} to review your link request and join {collective}. Once they accept, Continue setup appears here.',
  'banner.waiting.cta': 'View request',
  'banner.memberWaiting': 'You are part of {collective}. {host} is setting up the services and the shared booking page, so nothing is needed from you yet.',
  'banner.memberWaiting.cta': 'View collective',
  'setup.title': 'Link with a venue',
  'setup.step': 'Step {n} of {total}',
  'setup.venue.heading': 'Which venue?',
  'setup.venue.help': 'Search by name, or paste their booking page address.',
  'setup.venue.alreadyLinked': 'You are already linked with {venue}. To start a collective together, use Create a collective on this tab.',
  'setup.level.heading': 'How closely will you work together?',
  'setup.level.help': 'This sets what each venue can see and do in the other’s calendar. {venue} can adjust it before accepting, and either of you can change or end the link at any time.',
  'setup.level.mutual': 'The same both ways',
  'setup.level.customise': 'Customise permissions',
  'setup.level.custom': 'Custom permissions',
  'setup.level.customNote': 'A collective needs full access both ways, with no calendar limits.',
  'setup.collective.heading': 'Share one booking page?',
  'setup.collective.intro': 'With full access both ways you can also start a collective: one public booking page where clients book either venue as one business.',
  'setup.collective.no': 'Just link for now',
  'setup.collective.no.body': 'You can start a collective later from this tab.',
  'setup.collective.yes': 'Also start a collective',
  'setup.collective.yes.body': 'You will be the host. {venue} is asked to join when they accept the link.',
  'setup.collective.blocked': 'A collective with {venue} is not possible yet: {reason}',
  'setup.note.label': 'A note for {venue} (optional)',
  'setup.note.placeholder': 'Say hello, and why you want to link.',
  'setup.check.heading': 'Check and send',
  'setup.check.venue': 'Venue',
  'setup.check.level': 'Level of link',
  'setup.check.collective': 'Collective',
  'setup.check.collective.none': 'Not this time',
  'setup.check.collective.value': '{collective}, at /book/c/{slug}',
  'setup.check.note': 'Your note',
  'setup.check.whatTheyRead': 'What {venue} will read',
  'setup.check.theyCan': '{venue} will be able to:',
  'setup.check.youCan': 'You will be able to:',
  'setup.cta.send': 'Send request',
  'setup.cta.sending': 'Sending...',
  'setup.done.title': 'Request sent to {venue}',
  'setup.done.body': 'They have an email and a notice on their dashboard. Nothing changes until they accept.',
  'setup.done.next.link': 'When {venue} accepts, the link starts straight away.',
  'setup.done.next.collective': 'When {venue} accepts, they join {collective} and a banner on your dashboard shows you how to finish the page: choose the services, then the calendars.',
  'setup.done.next.where': 'The request is listed under Pending requests on this tab. You can cancel it there.',
  'setup.done.close': 'Done',
  'setup.done.next.watch': 'While you wait, a notice on your dashboard and on this tab says the request is with {venue}.',
  'setup.disabled.venue': 'Choose a venue to continue.',
  'setup.disabled.level': 'A link must grant access in at least one direction.',
  'setup.disabled.collective': 'Choose whether to start a collective.',
  'setup.changes.clients.body': 'The link you are sending is what lets the two venues see each other\'s client records and bookings, at the level you chose. {collective} does not change that link, and leaving or ending {collective} does not end it. Its reports show every venue\'s takings, each named.',
  'respond.title': '{venue} wants to link with you',
  'respond.titleWithCollective': '{venue} wants to link with you and start {collective}',
  'respond.step': 'Step {n} of {total}',
  'respond.request.heading': 'What {venue} is asking',
  'respond.request.theyCan': '{venue} will be able to:',
  'respond.request.youCan': 'You will be able to:',
  'respond.request.adjust': 'Adjust permissions',
  'respond.request.adjust.note': 'Changes to what you share apply as soon as you accept. Asking {venue} to share more is sent to them to agree.',
  'respond.request.dpa': 'Linking is a controller-to-controller data-sharing arrangement. Each venue stays the data controller for its own clients. You can reduce access or unlink at any time.',
  'respond.collective.heading': 'The shared booking page',
  'respond.collective.intro': '{venue} has also invited you to join {collective}, one booking page for both venues. Here is what that means for {me}.',
  'respond.collective.needsFull': 'Joining {collective} needs full access both ways with no calendar limits. With the permissions you chose you can accept the link only, and join later once the link grants full access.',
  'respond.collective.linkOnly': 'Accept the link only',
  'respond.collective.linkOnly.note': 'Accept the link only: the link starts now and the invitation to {collective} stays open on this tab for later.',
  'respond.check.heading': 'Check and accept',
  'respond.check.link': 'The link with {venue} starts as soon as you accept.',
  'respond.consent': 'I understand what {venue} will be able to see and do, and that {me} joins {collective}: guests who open my booking page land on the {collective} page, {venue} manages the services on it, and through this link the venues can see each other’s clients, bookings and takings.',
  'respond.consent.linkOnly': 'I understand what {venue} will be able to see and do with {me}’s data.',
  'respond.cta.accept': 'Accept',
  'respond.cta.acceptJoin': 'Accept and join {collective}',
  'respond.cta.accepting': 'Accepting...',
  'respond.cta.decline': 'Decline',
  'respond.cta.next': 'Next',
  'respond.cta.back': 'Back',
  'respond.decline.title': 'Decline {venue}’s request?',
  'respond.decline.body': 'No link is made. {venue} is told, without a reason.',
  'respond.decline.bodyWithCollective': 'No link is made and the invitation to {collective} closes. {venue} is told, without a reason.',
  'respond.decline.confirm': 'Decline request',
  'respond.done.linked': 'You are now linked with {venue}.',
  'respond.done.joined': 'You are now linked with {venue} and part of {collective}. {venue} is setting up the page.',
  'respond.done.joinFailed': 'The link with {venue} is active, but joining {collective} did not finish: {error} You can join from the collective’s row on this tab.',
  'respond.loading': 'Loading the request...',
  'respond.done.linked.title': 'You are linked with {venue}',
  'respond.done.joined.title': 'You are linked with {venue} and part of {collective}',
  'respond.done.linked.next': 'The link is active now. Open your Appointment Calendar to see {venue}’s columns alongside your own.',
  'respond.done.joined.next.host': 'Nothing is needed from you yet: {venue} is now setting up the services and the shared booking page for {collective}. A notice on your dashboard says so until the page is live.',
  'respond.done.joined.next.own': 'Your own booking page carries on as it is until the {collective} page is live. You will be told when it is.',
  'respond.done.joined.next.calendars': 'Once the services arrive, choose which of your calendars offer them under Calendar Availability, or let {venue} choose.',
  'respond.done.close': 'Done',
  'la.row.host.waiting': 'Waiting for {venueList} to accept your link request and join. Once they do, Continue setup appears here and on your dashboard.',
  'la.row.member.waiting': '{host} is setting up the services and the shared booking page. Nothing is needed from you yet.',
  'la.sent.collective': 'Also invites {venue} to join {collective}. Once they accept, Continue setup appears here.',
  'finish.title': 'Finish setting up {collective}',
  'finish.step': 'Step {n} of {total}',
  'finish.intro.heading': '{venueList} is in',
  'finish.intro.body': 'Two steps make the {collective} page live. First choose which of your services it offers. Then choose which calendars, at each venue, do them.',
  'finish.intro.owns': 'Each venue keeps its own bookings, clients and payments. You manage the services on the page; every venue can choose its own calendars.',
  'finish.services.heading': 'Which services go on the page?',
  'finish.services.help': 'These are your services. Guests see them on the {collective} page, and every venue’s calendars can offer them. Untick any you want to keep off the page for now.',
  'finish.services.none.title': 'You have no services yet',
  'finish.services.none.body': 'Add your first service here. Descriptions, photos and more can be added later on your Services page.',
  'finish.services.add': 'Add a service',
  'finish.services.add.name': 'Service name',
  'finish.services.add.duration': 'Length in minutes',
  'finish.services.add.price': 'Price',
  'finish.services.add.cta': 'Add service',
  'finish.services.add.adding': 'Adding...',
  'finish.services.selected': '{count} services selected',
  'finish.services.selectedOne': '{count} service selected',
  'finish.services.staffOnly': 'Staff bookings only',
  'finish.services.onPage': 'Already on the page',
  'finish.services.sameName': '{venueList} has a {service} too. They will be asked whether to use theirs for it.',
  'finish.calendars.awaiting': '{venue} has a service with the same name and has been asked whether to use it. Its calendars can be chosen once it answers, from the Collective area.',
  'svc.cal.warn.awaiting': '{venue} has a service with the same name and has been asked whether to use it. Its calendars can offer this once it answers.',
  'finish.services.saving': 'Putting the services on the page...',
  'finish.services.waiting': 'Setting the services up at {venueList}...',
  'finish.services.failed': '{count} services could not be put on the page. You can try again from your Services page.',
  'finish.calendars.heading': 'Who does what?',
  'finish.calendars.help': 'Tick the calendars that offer each service. Guests only see a service once at least one calendar offers it. Every venue can change its own calendars later under Calendar Availability.',
  'finish.calendars.all': 'All calendars',
  'finish.calendars.notReady': '{venue} is still being set up. Its calendars can be chosen in a moment, or later from the Collective area.',
  'finish.calendars.noCalendars': '{venue} has no active calendars yet.',
  'finish.calendars.saving': 'Saving calendars...',
  'finish.calendars.failed': '{count} calendar choices could not be saved. You can try them again from the Collective area.',
  'finish.done.title': '{collective} is live',
  'finish.done.body': 'Guests who open any of your venues’ booking pages now land on the {collective} page.',
  'finish.done.notLive.title': '{collective} is almost ready',
  'finish.done.notLive.body': 'Nothing can be booked until at least one calendar offers one service. You can finish this from the Collective area.',
  'finish.done.copy': 'Copy address',
  'finish.done.open': 'Open the page',
  'finish.done.design': 'Design the page',
  'finish.done.design.body': 'Colours, photos and the welcome text, under Settings, Booking Page.',
  'finish.done.area': 'Manage the collective',
  'finish.done.area.body': 'Services, venues and history, all in one place.',
  'finish.done.close': 'Done',
  'finish.cta.next': 'Continue',
  'finish.cta.back': 'Back',
  'finish.cta.save': 'Save and continue',
  'finish.cta.later': 'Do this later',
  'finish.row.cta': 'Continue setup',
  'finish.row.notLive': 'Not live yet: choose the services and calendars for the page.',
  'la.row.invitation.pendingLink': 'Review {host}’s link request on this tab to answer this invitation.',
} as const;

export type SetupCopyId = keyof typeof SETUP_COPY;

export function setupCopy(id: SetupCopyId, params: Record<string, string | number | null | undefined> = {}): string {
  return SETUP_COPY[id].replace(/\{(\w+)\}/g, (match, key: string) => {
    const value = params[key];
    return value === null || value === undefined ? match : String(value);
  });
}

/** "A", "A and B", "A, B and C", or "A, B and 2 more" (web `formatVenueList`). */
export function formatVenueList(names: readonly string[], namesShownWhenLong = 2): string {
  const clean = names.map((n) => n.trim()).filter(Boolean);
  if (clean.length === 0) return '';
  if (clean.length === 1) return clean[0]!;
  if (clean.length <= 3) return `${clean.slice(0, -1).join(', ')} and ${clean[clean.length - 1]}`;
  const shown = clean.slice(0, namesShownWhenLong);
  return `${shown.join(', ')} and ${clean.length - shown.length} more`;
}
